const gachaItems = {
    "3": {
        "A": {
            "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{2n+11}{n^{2}+2n+4}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{2n+11}{n^{2}+2n+4}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{2+\\dfrac{11}{n}}{n+2+\\dfrac{4}{n}}$</p><p>$=\\boldsymbol{0}$</p>",
    // 普通，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+3)(4n+1)}{n^{2}-5n+1}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+3)(4n+1)}{n^{2}-5n+1}$</p><p>$=\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\left(1+\\dfrac{3}{n}\\right)\\left(4+\\dfrac{1}{n}\\right)}{1-\\dfrac{5}{n}+\\dfrac{1}{n^{2}}}$</p><p>$=\\boldsymbol{4}$</p>",
    // 普通，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{_{2n+2}{\\rm C}_{n+1}}{_{2n}{\\rm C}_{n}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{_{2n+2}{\\rm C}_{n+1}}{_{2n}{\\rm C}_{n}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{(2n+2)!}{(n+1)!(n+1!)}\\cdot \\dfrac{n!n!}{2n!}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{(2n+2)(2n+1)}{(n+1)^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{2\\left(2+\\dfrac{1}{n}\\right)}{1+\\dfrac{1}{n}}$</p>",
    // 普通，2023関西大
    "$\\displaystyle \\lim_{n \\to \\infty}(\\sqrt{n^{2}+5n-3}-\\sqrt{n^{2}+1})$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}(\\sqrt{n^{2}+5n-3}-\\sqrt{n^{2}+1})$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}(\\sqrt{n^{2}+5n-3}-\\sqrt{n^{2}+1})\\cdot\\dfrac{\\sqrt{n^{2}+5n-3}+\\sqrt{n^{2}+1}}{\\sqrt{n^{2}+5n-3}+\\sqrt{n^{2}+1}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{(n^{2}+5n-3)-(n^{2}+1)}{\\sqrt{n^{2}+5n-3}+\\sqrt{n^{2}+1}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{5n-4}{\\sqrt{n^{2}+5n-3}+\\sqrt{n^{2}+1}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{5-\\dfrac{4}{n}}{\\sqrt{1+\\dfrac{5}{n}-\\dfrac{3}{n^2}}+\\sqrt{1+\\dfrac{1}{n^2}}}$</p><p>$=\\dfrac{5}{1+1}=\\boldsymbol{\\dfrac{5}{2}}$</p>",
    // 普通，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1+2+\\cdots+n}{n^2}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1+2+\\cdots+n}{n^2}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\dfrac{1}{2}n(n+1)}{n^2}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{2}\\left(1+\\dfrac{1}{n}\\right)$</p><p>$=\\boldsymbol{\\dfrac{1}{2}}$</p>",
    //普通の極限，ごよ１
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{3n^{2}+n+1}{n+1}-3n\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{3n^{2}+n+1}{n+1}-3n\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{-2n+1}{n+1}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{-2+\\dfrac{1}{n}}{1+\\dfrac{1}{n}}$</p><p>$=\\boldsymbol{-2}$</p>",
    //普通，ごよ２
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{\\sqrt{n^{2}+n}-n}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{\\sqrt{n^{2}+n}-n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{\\sqrt{n^{2}+n}-n}\\cdot \\dfrac{\\sqrt{n^{2}+n}+n}{\\sqrt{n^{2}+n}+n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\sqrt{n^{2}+n}+n}{n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sqrt{1+\\dfrac{1}{n}}+1$</p><p>$=\\boldsymbol{2}$</p>",
    //有理化，ごよ３
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sqrt{n+1}-\\sqrt{n-3}}{\\sqrt{n+2}-\\sqrt{n-2}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sqrt{n+1}-\\sqrt{n-3}}{\\sqrt{n+2}-\\sqrt{n-2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\sqrt{n+1}-\\sqrt{n-3}}{\\sqrt{n+2}-\\sqrt{n-2}}\\cdot\\dfrac{\\sqrt{n+2}+\\sqrt{n-2}}{\\sqrt{n+2}+\\sqrt{n-2}}\\cdot\\dfrac{\\sqrt{n+1}+\\sqrt{n-3}}{\\sqrt{n+1}+\\sqrt{n-3}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{4}{4}\\cdot\\dfrac{\\sqrt{n+2}+\\sqrt{n-2}}{\\sqrt{n+1}+\\sqrt{n-3}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\sqrt{1+\\dfrac{2}{n}}+\\sqrt{1-\\dfrac{2}{n}}}{\\sqrt{1+\\dfrac{1}{n}}+\\sqrt{1-\\dfrac{3}{n}}}$</p><p>$=\\boldsymbol{1}$</p>",
    //有理化，Z会M3JA2
    "$\\displaystyle \\lim_{n \\to \\infty} \\log_3 \\dfrac{\\sqrt[n]{7}}{5^n}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\log_3 \\dfrac{\\sqrt[n]{7}}{5^n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\left(\\log_3 \\sqrt[n]{7} -\\log_3{5^n}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\left(\\dfrac{1}{n}\\log_3 7 -n\\log_3 5\\right)$</p><p>$=\\boldsymbol{-\\infty}$</p>",
    //対数，ごよ４
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+1)+(n+2)+\\cdots+2n}{1+2+\\cdots+n}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+1)+(n+2)+\\cdots+2n}{1+2+\\cdots+n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{(n+1+2n)n\\cdot \\dfrac{1}{2}}{\\sum\\limits_{k=1}^{n}k}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{3n+1}{n+1}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{3+\\dfrac{1}{n}}{1+\\dfrac{1}{n}}$</p><p>$=\\boldsymbol{3}$</p>",
    //和，ごよ５，アプリ版専用
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sin n}{n}$": "<p>Since $-1\\leqq \\sin n \\leqq 1$</p><p style=\"text-align: center\">$-\\dfrac{1}{n}\\leqq \\dfrac{\\sin n}{n} \\leqq \\dfrac{1}{n}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\left(-\\dfrac{1}{n}\\right)=\\lim_{n \\to \\infty}\\dfrac{1}{n}=0$ より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sin n}{n}=\\boldsymbol{0}$</p>",
    // はさみうち，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n^{2}+1}+\\dfrac{1}{n^{2}+2}+\\cdots+\\dfrac{1}{n^{2}+n}\\right)$ ": "<p>$\\displaystyle A_n=\\dfrac{1}{n^{2}+1}+\\dfrac{1}{n^{2}+2}+\\cdots+\\dfrac{1}{n^{2}+n}$ とおく．</p><p>$\\displaystyle 0 &lt; \\dfrac{1}{n^{2}+k} &lt; \\dfrac{1}{n^2}$ $(k=1,2,\\cdots,n)$ だから</p><p>$\\displaystyle 0 &lt; A_n &lt; \\dfrac{1}{n^2}+\\dfrac{1}{n^2}+\\cdots+\\dfrac{1}{n^2}=\\dfrac{1}{n^2}\\cdot n=\\dfrac{1}{n}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n}=0$ より $\\displaystyle \\lim_{n \\to \\infty}A_n=\\boldsymbol{0}$</p>",
    //はさみうち，ごよ６
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{2(-3)^{n}+7\\cdot5^{n+1}}{5\\cdot3^{n+1}-2\\cdot 5^{n}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{2(-3)^{n}+7\\cdot5^{n+1}}{5\\cdot3^{n+1}-2\\cdot 5^{n}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{2\\left(-\\dfrac{3}{5}\\right)^{n}+35}{15\\left(\\dfrac{3}{5}\\right)^{n}-2}$</p><p>$=\\boldsymbol{-\\dfrac{35}{2}}$</p>",
    // 無限等比数列，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\{5^{n}-(-4)^n\\}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\{5^{n}-(-4)^n\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}5^{n} \\left\\{1- \\left( -\\dfrac{4}{5} \\right)^n \\right\\}$</p><p>$=\\boldsymbol{\\infty}$</p>",
    //等比，ごよ７
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{x^{n}+x+1}{x^{2n}+1}$　$( \\ x \\ is a real number \\ )$": "<p>Set $\\displaystyle f(x)=\\dfrac{x^{n}+x+1}{x^{2n}+1}$</p>(ⅰ) When $|x|&lt;1$</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)$</p><p>$\\displaystyle =\\dfrac{0+x+1}{0+1}=x+1$</p><br><p>(ⅱ) $|x|&gt;1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\dfrac{1}{x^{n}}+\\dfrac{x+1}{x^{2n}}}{1+\\dfrac{1}{x^{2n}}}=0$</p><br><p>(ⅲ) $x=1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\dfrac{3}{2}$</p><br><p>(ⅳ) $x=-1$ のとき</p><p>分子の $x^{n}$ が振動するので定義されない．</p><p>以上より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\begin{cases} \\boldsymbol{x+1 \\ \\ \\ (-1&lt; x &lt; 1)} \\\\ \\boldsymbol{0 \\ \\ \\ (x&lt;-1，1&lt;x)} \\\\ \\boldsymbol{\\dfrac{3}{2} \\ \\ \\ (x=1)}\\end{cases}$</p>",
    // 無限等比数列，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{x^{2n+1}-1}{x^{2n}+1}$　$( \\ x \\ is a real number \\ )$": "<p>Set $\\displaystyle f(x)=\\dfrac{x^{2n+1}-1}{x^{2n}+1}$.</p><p>(i) When $ |x| < 1$</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\dfrac{0-1}{0+1}=-1$</p><p>(ii) $ |x| > 1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\lim_{n \\to \\infty}\\dfrac{x-\\dfrac{1}{x^{2n}}}{1+\\dfrac{1}{x^{2n}}}=x$</p><p>(iii) $ x=1 $ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\dfrac{1-1}{1+1}=0$</p><p>(iv) $ x=-1 $ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\dfrac{-1-1}{1+1}=-1$</p><p>以上より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\begin{cases} \\boldsymbol{-1 \\ \\ \\ (-1 \\leqq x < 1)} \\\\ \\boldsymbol{x \\ \\ \\ (x &lt; -1，1&lt;x)} \\\\ \\boldsymbol{0 \\ \\ \\ (x=1)}\\end{cases}$</p>",
    //等比場合分け，ごよ８
    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\dfrac{1}{(2k+1)(2k+3)}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\dfrac{1}{(2k+1)(2k+3)}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\dfrac{1}{2}\\left(\\dfrac{1}{2k+1}-\\dfrac{1}{2k+3}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{2}\\sum_{k=1}^{n}\\left(\\dfrac{1}{2k+1}-\\dfrac{1}{2k+3}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{2}\\left\\{\\left(\\dfrac{1}{3}-\\dfrac{1}{5}\\right)+\\left(\\dfrac{1}{5}-\\dfrac{1}{7}\\right)+\\cdots+\\left(\\dfrac{1}{2n+1}-\\dfrac{1}{2n+3}\\right)\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{2}\\left(\\dfrac{1}{3}-\\dfrac{1}{2n+3}\\right)$</p><p>$=\\boldsymbol{\\dfrac{1}{6}}$</p>",
    // 無限級数，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\left(\\dfrac{1}{3^{k-1}}-\\dfrac{1}{4^{k}}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\left(\\dfrac{1}{3^{k-1}}-\\dfrac{1}{4^{k}}\\right)$</p><p>$=\\dfrac{1}{1-\\dfrac{1}{3}}-\\dfrac{\\dfrac{1}{4}}{1-\\dfrac{1}{4}}$</p><p>$\\displaystyle =\\dfrac{3}{2}-\\dfrac{1}{3}=\\boldsymbol{\\dfrac{7}{6}}$</p>",
    // 無限級数，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\left\\{2\\left(-\\dfrac{2}{3}\\right)^{k-1}+3\\left(\\dfrac{1}{4}\\right)^{k-1}\\right\\}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\left\\{2\\left(-\\dfrac{2}{3}\\right)^{k-1}+3\\left(\\dfrac{1}{4}\\right)^{k-1}\\right\\}$</p><p>$\\displaystyle =\\dfrac{2}{1- \\left(-\\dfrac{2}{3}\\right) }+\\dfrac{3}{1-\\dfrac{1}{4}}$</p><p>$\\displaystyle =\\dfrac{6}{5}+4$</p><p>$\\displaystyle =\\boldsymbol{\\dfrac{26}{5}}$</p>",
    //等比級数，ごよ９
    "$\\displaystyle \\lim_{x \\to 2}\\dfrac{x^{2}-5x+6}{x-2}$": "<p>　$\\displaystyle \\lim_{x \\to 2}\\dfrac{(x-2)(x-3)}{x-2}$</p><p>$\\displaystyle =\\lim_{x \\to 2}(x-3)$</p><p>$=\\boldsymbol{-1}$</p>",
    // 関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to 3}\\dfrac{\\sqrt{x+13}-4}{x-3}$": "<p>　$\\displaystyle \\lim_{x \\to 3}\\dfrac{\\sqrt{x+13}-4}{x-3}\\cdot\\dfrac{\\sqrt{x+13}+4}{\\sqrt{x+13}+4}$</p><p>$\\displaystyle =\\lim_{x \\to 3}\\dfrac{x-3}{(x-3)(\\sqrt{x+13}+4)}$</p><p>$\\displaystyle =\\lim_{x \\to 3}\\dfrac{1}{\\sqrt{x+13}+4}$</p><p>$\\displaystyle =\\boldsymbol{\\dfrac{1}{8}}$</p>",
    // 関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to -\\infty}(\\sqrt{x^{2}+5x}+x)$": "<p>　$\\displaystyle \\lim_{x \\to -\\infty}(\\sqrt{x^{2}+5x}+x)$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}(\\sqrt{x^{2}+5x}+x)\\cdot \\dfrac{\\sqrt{x^{2}+5x}-x}{\\sqrt{x^{2}+5x}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5x}{\\sqrt{x^{2}+5x}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5x}{\\sqrt{x^{2}}\\sqrt{1+\\dfrac{5}{x}}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5x}{|x|\\sqrt{1+\\dfrac{5}{x}}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5x}{-x\\sqrt{1+\\dfrac{5}{x}}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5}{-\\sqrt{1+\\dfrac{5}{x}}-1}$</p><p>$\\displaystyle =\\boldsymbol{-\\dfrac{5}{2}}$</p><p><b style=\"color: black\">別解</b></p><p>　$\\displaystyle \\lim_{x \\to -\\infty}(\\sqrt{x^{2}+5x}+x)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}(\\sqrt{t^{2}-5t}-t)$　$(t=-x)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}(\\sqrt{t^{2}-5t}-t)\\cdot \\dfrac{\\sqrt{t^{2}-5t}+t}{\\sqrt{t^{2}-5t}+t}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\dfrac{-5t}{\\sqrt{t^{2}-5t}+t}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\dfrac{-5}{\\sqrt{1-\\dfrac{5}{t}}+1}$</p><p>$\\displaystyle =\\boldsymbol{-\\dfrac{5}{2}}$</p>",
    // -∞有理化，サイトの例題
    "$\\displaystyle \\lim_{x \\to -\\infty} \\dfrac{4^x}{3^{x}+2^{x}}$": "<p>　$\\displaystyle \\lim_{x \\to -\\infty} \\dfrac{4^x}{3^x+2^x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty} \\dfrac{2^x}{\\left(\\dfrac{3}{2}\\right)^{x}+1}$</p><p>$\\displaystyle =\\dfrac{0}{0+1}$</p><p>$=\\boldsymbol{0}$</p>",
    //-∞，ごよ１４
    "$\\displaystyle \\lim_{x \\to -\\infty} \\left(3x+1+\\sqrt{9x^2+1}\\right)$": "<p>　$\\displaystyle \\lim_{x \\to -\\infty} \\left(3x+1+\\sqrt{9x^2+1}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty} \\dfrac{(3x+1)^2-(9x^2+1)}{3x+1-\\sqrt{9x^2+1}}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty} \\dfrac{6x}{3x+1+x\\sqrt{9+\\dfrac{1}{x^2}}}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty} \\dfrac{6}{3+\\dfrac{1}{x}+\\sqrt{9+\\dfrac{1}{x^2}}}$</p><p>$\\displaystyle =\\dfrac{6}{3+\\sqrt{9}}$</p><p>$\\displaystyle =\\boldsymbol{1}$</p><p><b style=\"color: black\">別解</b></p><p>　$\\displaystyle \\lim_{x \\to -\\infty} \\left(3x+1+\\sqrt{9x^2+1}\\right)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty} \\left(-3t+1+\\sqrt{9t^2+1}\\right)　(t=-x)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty} \\dfrac{(-3t+1)^2-(9t^2+1)}{-3t+1-\\sqrt{9t^2+1}}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty} \\dfrac{-6t}{-3t+1-\\sqrt{9t^2+1}}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty} \\dfrac{-6}{-3+\\dfrac{1}{t}-\\sqrt{9+\\dfrac{1}{t^2}}}$</p><p>$\\displaystyle =\\dfrac{-6}{-3-\\sqrt{9}}$</p><p>$\\displaystyle =\\boldsymbol{1}$</p>",
    //-∞有理化，ごよ１５
    "$\\displaystyle \\lim_{x \\to -5+0}\\dfrac{x}{x+5}$": "<p>　$\\displaystyle \\lim_{x \\to -5+0}\\dfrac{x}{x+5}=\\boldsymbol{-\\infty}$</p>",
    // 関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to -2}\\dfrac{x^{3}+3x^{2}-4}{x^{3}+8}$": "<p>　$\\displaystyle \\lim_{x \\to -2}\\dfrac{x^{3}+3x^{2}-4}{x^{3}+8}$</p><p>$\\displaystyle =\\lim_{x \\to -2}\\dfrac{(x+2)^{2}(x-1)}{(x+2)(x^{2}-2x+4)}$</p><p>$\\displaystyle =\\lim_{x \\to -2}\\dfrac{(x+2)(x-1)}{x^{2}-2x+4}$</p><p>$\\displaystyle =\\dfrac{0 \\cdot (-3)}{12}$</p><p>$=\\boldsymbol{0}$</p>",
    //普通関数，ごよ１１
    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{1}{x} \\left(\\dfrac{3}{x+3}-1\\right)$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{1}{x} \\left(\\dfrac{3}{x+3}-1\\right)$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{1}{x}\\left(\\dfrac{-x}{x+3}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\left(-\\dfrac{1}{x+3}\\right)$</p><p>$ =\\boldsymbol{-\\dfrac{1}{3}}$</p>",
    //普通関数，ごよ１２
    "$\\displaystyle \\lim_{x \\to 2}\\dfrac{-2x+4}{\\sqrt{2x}-\\sqrt{x+2}}$": "<p>　$\\displaystyle \\lim_{x \\to 2}\\dfrac{-2x+4}{\\sqrt{2x}-\\sqrt{x+2}}$</p><p>$\\displaystyle =\\lim_{x \\to 2}\\dfrac{-2x+4}{2x-(x+2)} \\cdot \\left(\\sqrt{2x}+\\sqrt{x+2}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to 2}\\dfrac{-2x+4}{x-2} \\cdot \\left(\\sqrt{2x}+\\sqrt{x+2}\\right)$</p><p>$\\displaystyle =(-2) \\cdot \\left(\\sqrt{4}+\\sqrt{4} \\right)$</p><p>$=\\boldsymbol{-8}$</p>",
    //有理化関数，ごよ１３
    "$\\displaystyle \\lim_{x \\to \\infty}\\{\\log_2 (8x^2+2)-2\\log_2 (x+3)\\}$": "<p>　$\\displaystyle \\lim_{x \\to \\infty}\\{\\log_2 (8x^2+2)-2\\log_2 (x+3)\\}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\{\\log_2 (8x^2+2)-\\log_2 (x+3)^2\\}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} \\log_2 \\dfrac{8x^2+2}{(x+3)^2}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} \\log_2 \\dfrac{8+\\dfrac{2}{x^2}}{ \\left(1+\\dfrac{3}{x}\\right)^2}$</p><p>$\\displaystyle =\\log_2 8$</p><p>$=\\boldsymbol{3}$</p>",
    //対数，ごよ１６
    "$\\displaystyle \\lim_{x \\to \\infty}\\left(\\dfrac{b}{a}x-\\dfrac{b}{a}\\sqrt{x^{2}-a^{2}}\\right)$　$( \\ a,b \\ are positive real numbers)$": "<p>　$\\displaystyle \\lim_{x \\to \\infty}\\left(\\dfrac{b}{a}x-\\dfrac{b}{a}\\sqrt{x^{2}-a^{2}}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\dfrac{b}{a}\\left(x-\\sqrt{x^{2}-a^{2}}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\dfrac{b}{a}\\left(\\dfrac{a^2}{x+\\sqrt{x^{2}-a^{2}}}\\right)$</p><p>$=\\boldsymbol{0}$</p>",
    //双曲線の漸近線，アプリ版専用
    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{1-\\cos x}{x\\sin x}$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{1-\\cos x}{x\\sin x} \\cdot \\dfrac{1+\\cos x}{1+\\cos x}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{\\sin^{2} x}{x\\sin x (1+\\cos x)}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{\\sin x}{x}\\cdot \\dfrac{1}{1+\\cos x}$</p><p>$=1\\cdot \\dfrac{1}{2}=\\boldsymbol{\\dfrac{1}{2}}$</p>",
    // 三角関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin \\left(\\sin \\dfrac{x}{\\pi}\\right)}{\\pi x}$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin \\left(\\sin \\dfrac{x}{\\pi}\\right)}{\\pi x}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{\\sin \\left(\\sin \\dfrac{x}{\\pi}\\right)}{\\sin \\dfrac{x}{\\pi}}\\cdot \\dfrac{\\sin \\dfrac{x}{\\pi}}{\\dfrac{x}{\\pi}}\\cdot \\dfrac{1}{\\pi^{2}}$</p><p>$=\\boldsymbol{\\dfrac{1}{\\pi^{2}}}$</p>",
    // 三角関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to \\frac{\\pi}{2}} \\dfrac{\\cos x}{2x-\\pi}$": "<p>　$\\displaystyle \\lim_{x \\to \\frac{\\pi}{2}} \\dfrac{\\cos x}{2x-\\pi}$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{\\cos \\left(t+\\dfrac{\\pi}{2}\\right)}{2t}　\\left(t=x-\\dfrac{\\pi}{2}\\right)$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{-\\sin t}{2t}$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\left(-\\dfrac{1}{2} \\right)\\dfrac{\\sin t}{t}$</p><p>$=\\boldsymbol{-\\dfrac{1}{2}}$</p>",
    //三角関数，ごよ１８
    "$\\displaystyle \\lim_{x \\to 0} \\dfrac{\\tan 3x}{\\sin 5x}$": "<p>　$\\displaystyle \\lim_{x \\to 0} \\dfrac{\\tan 3x}{\\sin 5x}$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\dfrac{\\tan 3x}{3x} \\cdot \\dfrac{5x}{\\sin 5x} \\cdot \\dfrac{3}{5}$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\dfrac{\\sin 3x}{3x} \\cdot \\dfrac{1}{\\cos 3x} \\cdot\\dfrac{5x}{\\sin 5x} \\cdot \\dfrac{3}{5}$</p><p>$\\displaystyle =1 \\cdot 1 \\cdot 1 \\cdot \\dfrac{3}{5}$</p><p>$=\\boldsymbol{\\dfrac{3}{5}}$</p>",
    //三角関数，2023東京都市大，元はごよさんの問題
    "$\\displaystyle \\lim_{x \\to 0} \\dfrac{\\sin 3x-\\sin 7x}{\\sin 2x}$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin 3x-\\sin 7x}{\\sin 2x}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\left(\\dfrac{\\sin 3x}{\\sin 2x}-\\dfrac{\\sin 7x}{\\sin 2x}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\left(\\dfrac{\\sin 3x}{3x}\\cdot\\dfrac{2x}{\\sin 2x}\\cdot\\dfrac{3}{2}-\\dfrac{\\sin 7x}{7x}\\cdot\\dfrac{2x}{\\sin 2x}\\cdot\\dfrac{7}{2}\\right)$</p><p>$=1\\cdot 1\\cdot \\dfrac{3}{2}-1\\cdot 1\\cdot \\dfrac{7}{2}$</p><p>$=\\boldsymbol{-2}$</p>",
    //三角関数，2022東京都市大
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+2}+\\dfrac{1}{n+4}+\\cdots+\\dfrac{1}{3n}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+2}+\\dfrac{1}{n+4}+\\cdots+\\dfrac{1}{n+2n}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\frac{1}{n+2k}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\frac{1}{n}\\sum_{k=1}^{n}\\frac{1}{1+2\\dfrac{k}{n}}$</p><p>$\\displaystyle =\\int_{0}^{1}\\dfrac{1}{1+2x}\\,dx$</p><p>$\\displaystyle =\\left[\\frac{1}{2}\\log(1+2x)\\right]_{0}^{1}$</p><p>$\\displaystyle =\\boldsymbol{\\frac{1}{2}\\log3}$</p>",
    // 区分求積，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n}\\left(\\sin^{2}\\dfrac{\\pi}{4n}+\\sin^{2}\\dfrac{2\\pi}{4n}+\\cdots+\\sin^{2}\\dfrac{\\pi}{4}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n}\\left(\\sin^{2}\\dfrac{\\pi}{4n}+\\sin^{2}\\dfrac{2\\pi}{4n}+\\cdots+\\sin^{2}\\dfrac{\\pi}{4}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=1}^{n}\\sin^{2}\\dfrac{k\\pi}{4n}$</p><p>$\\displaystyle =\\int_{0}^{1}\\sin^{2}\\dfrac{\\pi x}{4}\\,dx$</p><p>$\\displaystyle =\\int_{0}^{1}\\dfrac{1}{2}\\left(1-\\cos\\dfrac{\\pi x}{2}\\right)\\,dx$</p><p>$\\displaystyle =\\left[\\dfrac{1}{2}x-\\dfrac{1}{\\pi}\\sin\\dfrac{\\pi x}{2}\\right]_{0}^{1}$</p><p>$=\\boldsymbol{\\dfrac{\\pi-2}{2\\pi}}$</p>",
    // 区分求積
    "$\\displaystyle \\lim_{n \\to \\infty} \\sum\\limits_{k=1}^{n} \\sqrt{\\dfrac{n+k}{n^3}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\sum\\limits_{k=1}^n  \\sqrt{\\dfrac{n+k}{n^3}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{n} \\sum\\limits_{k=1}^n \\sqrt{1+\\dfrac{k}{n}}$</p><p>$\\displaystyle =\\int_{0}^{1} (1+x)^\\frac{1}{2} dx$</p><p>$\\displaystyle =\\left[\\dfrac{2}{3} (1+x)^\\frac{3}{2} \\right]^1_0$</p><p>$=\\boldsymbol{\\dfrac{2}{3}\\left(2\\sqrt{2}-1\\right)}$</p>",
    //区分求積，ごよ１９
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n^{2}+1^{2}}+\\dfrac{2}{n^{2}+2^{2}}+\\dfrac{3}{n^{2}+3^{2}}+\\cdots+\\dfrac{1}{2n}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n^{2}+1^{2}}+\\dfrac{2}{n^{2}+2^{2}}+\\dfrac{3}{n^{2}+3^{2}}+\\cdots+\\dfrac{1}{2n}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\frac{k}{n^{2}+k^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=1}^{n}\\frac{\\dfrac{k}{n}}{1+\\left(\\dfrac{k}{n}\\right)^{2}}$</p><p>$\\displaystyle =\\int_{0}^{1}\\dfrac{x}{1+x^{2}}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{2}\\int_{0}^{1}\\dfrac{2x}{1+x^{2}}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{2}\\Bigl[\\log(1+x^{2})\\Bigr]_{0}^{1}$</p><p>$\\displaystyle =\\boldsymbol{\\dfrac{1}{2}\\log 2}$</p>",
    //区分求積，アプリ版専用
    "$\\displaystyle \\lim_{x \\to \\infty} \\dfrac{[3x]}{x}$": "<p>$3x-1 &lt; [3x] \\leqq 3x$ が成り立つ．各辺 $x$ で割ると</p><p style=\"text-align: center\">$\\dfrac{3x-1}{x} &lt; \\dfrac{[3x]}{x} \\leqq \\dfrac{3x}{x}$</p><p style=\"text-align: center\">$\\displaystyle 3-\\dfrac{1}{x} &lt; \\dfrac{[3x]}{x} \\leqq 3$</p><p>$\\displaystyle \\lim_{x \\to \\infty} \\left(3-\\dfrac{1}{x} \\right)=3$ だから $\\displaystyle \\lim_{x \\to \\infty} \\dfrac{[3x]}{x}=\\boldsymbol{3}$</p>",
    //ガウス，ごよ１７
    "$\\displaystyle \\lim_{x \\to 1}\\left(2x-[x]\\right)\\left([x]+1\\right)$": "<p>　$\\displaystyle \\lim_{x \\to 1+0}\\left(2x-[x]\\right)\\left([x]+1\\right)$</p><p>$=(2-1)(1+1)$</p><p>$=2$</p><p>　$\\displaystyle \\lim_{x \\to 1-0}\\left(2x-[x]\\right)\\left([x]+1\\right)$</p><p>$=(2-0)(0+1)$</p><p>$=2$</p><p>　$\\displaystyle \\therefore \\ \\lim_{x \\to 1}\\left(2x-[x]\\right)\\left([x]+1\\right)=\\boldsymbol{2}$</p>",
    //ガウス，片側極限
        },
        "B": {
            "$\\displaystyle \\lim_{n \\to \\infty}\\left(1-1+\\dfrac{1}{2}-\\dfrac{1}{2}+\\cdots+\\dfrac{4(-1)^{n-1}}{2n+1+(-1)^{n-1}}\\right)$": "<p>$S_{n}=1-1+\\dfrac{1}{2}-\\dfrac{1}{2}+\\cdots+\\dfrac{4(-1)^{n-1}}{2n+1+(-1)^{n-1}}$ とする．</p><p>$\\displaystyle S_{2n}=(1-1)+\\left(\\dfrac{1}{2}-\\dfrac{1}{2}\\right)+\\cdots+\\left(\\dfrac{1}{n}-\\dfrac{1}{n}\\right)=0$</p><p>$\\displaystyle S_{2n-1}=(1-1)+\\left(\\dfrac{1}{2}-\\dfrac{1}{2}\\right)+\\cdots+\\dfrac{1}{n}=\\dfrac{1}{n}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}S_{2n}=0$，$\\displaystyle \\lim_{n \\to \\infty}S_{2n-1}=\\lim_{n \\to \\infty}\\dfrac{1}{n}=0$</p><p>よって $\\displaystyle \\lim_{n \\to \\infty}S_n=\\boldsymbol{0}$</p>",
    //２通りの部分和，ごよ１０
    "$\\displaystyle \\lim_{n \\to \\infty} \\sum_{k=1}^{n} \\dfrac{1}{2^{k}}\\sin \\dfrac{2k\\pi}{3}$": "<p>$\\displaystyle S_{n}=\\sum_{k=1}^{n} \\dfrac{1}{2^{k}}\\sin \\dfrac{2k\\pi}{3}$ とする</p><p>\\begin{align}S_{3n} &= \\dfrac{1}{2}\\sin \\dfrac{2\\pi}{3}+\\dfrac{1}{2^{2}}\\sin \\dfrac{4\\pi}{3}+\\dfrac{1}{2^{3}}\\sin 2\\pi 　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\\\\[6pt]& \\quad + \\dfrac{1}{2^{4}}\\sin \\dfrac{8\\pi}{3}+\\dfrac{1}{2^{5}}\\sin \\dfrac{10\\pi}{3}+\\dfrac{1}{2^{6}}\\sin 4\\pi+\\cdots\\\\[6pt]& \\quad + \\dfrac{1}{2^{3n-2}}\\sin\\left(2n\\pi-\\dfrac{4\\pi}{3}\\right)+\\dfrac{1}{2^{3n-1}}\\sin\\left(2n\\pi-\\dfrac{2\\pi}{3}\\right)+\\dfrac{1}{2^{3n}}\\sin 2n\\pi\\\\[12pt]&= \\dfrac{1}{2}\\cdot\\dfrac{\\sqrt{3}}{2}+\\dfrac{1}{2^{2}}\\cdot\\left(-\\dfrac{\\sqrt{3}}{2}\\right)+\\dfrac{1}{2^{3}}\\cdot0\\\\[6pt]& \\quad + \\dfrac{1}{2^{4}}\\cdot\\dfrac{\\sqrt{3}}{2}+\\dfrac{1}{2^{5}}\\cdot\\left(-\\dfrac{\\sqrt{3}}{2}\\right)+\\dfrac{1}{2^{6}}\\cdot0+\\cdots\\\\[6pt]& \\quad + \\dfrac{1}{2^{3n-2}}\\cdot\\dfrac{\\sqrt{3}}{2}+\\dfrac{1}{2^{3n-1}}\\cdot\\left(-\\dfrac{\\sqrt{3}}{2}\\right)+\\dfrac{1}{2^{3n}}\\cdot0\\\\[12pt]&= \\dfrac{\\sqrt{3}}{2}\\left(\\dfrac{1}{2}+\\dfrac{1}{2^{4}}+\\cdots+\\dfrac{1}{2^{3n-2}}\\right)\\\\[6pt]& \\quad -\\dfrac{\\sqrt{3}}{2}\\left(\\dfrac{1}{2^{2}}+\\dfrac{1}{2^{5}}+\\cdots+\\dfrac{1}{2^{3n-1}}\\right)+0\\\\[12pt]\\end{align}</p><p>\\begin{align}\\lim_{n \\to \\infty} S_{3n} &= \\dfrac{\\sqrt{3}}{2}\\cdot\\dfrac{\\dfrac{1}{2}}{1-\\dfrac{1}{2^{3}}}-\\dfrac{\\sqrt{3}}{2}\\cdot\\dfrac{\\dfrac{1}{2^{2}}}{1-\\dfrac{1}{2^{3}}}+0　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\\\\[6pt] &= \\dfrac{2\\sqrt{3}}{7}-\\dfrac{\\sqrt{3}}{7}=\\dfrac{\\sqrt{3}}{7}\\end{align}</p><p>$S_{3n-1}=S_{3n}-\\dfrac{1}{2^{3n}}\\cdot0$</p><p>$S_{3n-2}=S_{3n}-\\dfrac{1}{2^{3n}}\\cdot0-\\dfrac{1}{2^{3n-1}}\\left(-\\dfrac{\\sqrt{3}}{2}\\right)$</p><p>$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{1}{2^{3n-1}}\\left(-\\dfrac{\\sqrt{3}}{2}\\right)=0$ だから</p><p>$\\displaystyle \\lim_{n \\to \\infty} S_{3n}=\\lim_{n \\to \\infty} S_{3n-1}=\\lim_{n \\to \\infty} S_{3n-2}=\\dfrac{\\sqrt{3}}{7}$ より</p><p>　$\\displaystyle \\lim_{n \\to \\infty} \\sum\\limits_{k=1}^{n} \\dfrac{1}{2^{k}}\\sin \\dfrac{2k\\pi}{3}=\\boldsymbol{\\dfrac{\\sqrt{3}}{7}}$</p>",
    //３通りの部分和，ごよ７
    "$\\displaystyle \\lim_{x\\to 0}\\left(1+3x\\right)^{\\frac{2}{x}}$": "<p>　$\\displaystyle \\lim_{x\\to 0}\\left(1+3x\\right)^{\\frac{2}{x}}$</p><p>$=\\displaystyle \\lim_{t\\to 0}\\left(1+t\\right)^{\\frac{6}{t}}$　$(t=3x)$</p><p>$=\\displaystyle \\lim_{t\\to 0}\\left\\{\\left(1+t\\right)^{\\frac{1}{t}}\\right\\}^{6}$</p><p>$=\\boldsymbol{e^{6}}$</p>",
    // eの定義，サイトの例題
    "$\\displaystyle \\lim_{n\\to \\infty}\\left(\\dfrac{2n-1}{2n}\\right)^{5n}$": "<p>　$\\displaystyle \\lim_{n\\to \\infty}\\left(\\dfrac{2n-1}{2n}\\right)^{5n}$</p><p>$=\\displaystyle \\lim_{t\\to -0}\\left(1+t\\right)^{-\\frac{5}{2t}}$　$\\left(t=-\\dfrac{1}{2n}\\right)$</p><p>$=\\displaystyle \\lim_{t\\to -0}\\left\\{\\left(1+t\\right)^{\\frac{1}{t}}\\right\\}^{-\\frac{5}{2}}$</p><p>$=\\boldsymbol{e^{-\\frac{5}{2}}}$</p>",
    // eの定義，サイトの例題
    "$\\displaystyle \\lim_{x \\to 0} (\\cos^{2} x)^{\\frac{1}{x^{2}}}$": "<p>　$\\displaystyle \\lim_{x \\to 0} (\\cos^{2} x)^{\\frac{1}{x^{2}}}$</p><p>$\\displaystyle =\\lim_{x \\to 0} (1-\\sin^{2} x)^{\\frac{1}{x^{2}}}$</p><p>$\\displaystyle =\\lim_{x \\to 0} (1-\\sin^{2} x)^{\\left(-\\frac{1}{\\sin^{2} x}\\right) \\left(-\\frac{\\sin^{2} x}{x^{2}}\\right)}$</p><p>$x \\to 0$ のとき $\\sin^{2} x \\to 0$ だから</p><p>　$\\displaystyle \\lim_{x \\to 0} (\\cos^{2} x)^{\\frac{1}{x^{2}}}=\\boldsymbol{e^{-1}}$</p>",
    //eの定義，ごよ１６
    "$\\displaystyle \\lim_{x \\to 0} \\dfrac{1}{x}\\log\\{\\log(x+e)\\}$": "<p>$f(x)=\\log\\{\\log(x+e)\\}$ とおくと</p><p>　$\\displaystyle \\lim_{x \\to 0} \\dfrac{1}{x}\\log\\{\\log(x+e)\\}$</p><p>$=\\displaystyle \\lim_{x\\to 0}\\dfrac{f(x)-f(0)}{x-0}$</p><p>$=f'(0)$　$\\left(f'(x)=\\dfrac{1}{(x+e)\\log(x+e)}\\right)$</p><p>$=\\boldsymbol{\\dfrac{1}{e}}$</p>",
    // 微分係数の定義利用
    "$\\displaystyle \\lim_{x \\to 0} \\dfrac{2^{x}-1}{x}$": "<p>$f(x)=2^{x}$ とすると $f'(x)=2^{x}\\log 2$</p><p>　$\\displaystyle \\lim_{x \\to 0} \\dfrac{2^{x}-1}{x}$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\dfrac{f(x)-f(0)}{x-0}$</p><p>$=f'(0)$</p><p>$=\\boldsymbol{\\log 2}$</p>",
    //微分係数，ごよ１５
    "$\\displaystyle \\lim_{x \\to \\infty} (xe^{\\frac{1}{x}}-x-1)$": "<p>　$\\displaystyle \\lim_{x \\to \\infty} (xe^{\\frac{1}{x}}-x-1)$</p><p>$\\displaystyle =\\lim_{t \\to +0} \\left(\\dfrac{e^{t}-1}{t}-1\\right)$　$\\left(t=\\dfrac{1}{x}\\right)$</p><p>$=1-1$</p><p>$=\\boldsymbol{0}$</p>",
    // 微分係数の定義利用，置き換え，xe^{1/x}の漸近線
    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{1}{x}\\int_{0}^{x}e^{t}\\cos t\\,dt$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{1}{x}\\int_{0}^{x}e^{t}\\cos t\\,dt$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{F(x)-F(0)}{x-0}$ $(f(x)=e^{x}\\cos x)$</p><p>$=f(0)$</p><p>$=\\boldsymbol{1}$</p>",
    // 微分係数の定義利用
    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin 2x}{\\log_{2}(x+2)-1}$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin 2x}{\\log_{2}(x+2)-1}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{\\sin 2x}{x}\\cdot\\dfrac{x}{\\log_{2}(x+2)-\\log_{2}2}$</p><p>$\\displaystyle =\\lim_{x \\to 0}2\\cdot\\dfrac{\\sin 2x}{2x}\\cdot\\dfrac{1}{\\dfrac{1}{x}\\log_{2}\\left(\\dfrac{x}{2}+1\\right)}$</p><p>$\\displaystyle =\\lim_{x \\to 0}2\\cdot\\dfrac{\\sin 2x}{2x}\\cdot\\dfrac{2}{\\dfrac{2}{x}\\log_{2}\\left(1+\\dfrac{x}{2}\\right)}$</p><p>$\\displaystyle =\\lim_{x \\to 0}2\\cdot\\dfrac{\\sin 2x}{2x}\\cdot\\dfrac{2}{\\log_{2}\\left(1+\\dfrac{x}{2}\\right)^{\\frac{2}{x}}}$</p><p>$=2\\cdot 1\\cdot \\dfrac{2}{\\log_{2}e}$</p><p>$=\\boldsymbol{4\\log2}$</p>",
    // 三角関数の極限，eの定義(微分係数の定義)利用，2023福島県立医大
    "$\\displaystyle \\lim_{h \\to 0} \\dfrac{(x+h)^{n}-x^{n}}{h}$　$( \\ n \\ は自然数 \\ )$": "<p>　$\\displaystyle \\lim_{h \\to 0} \\dfrac{(x+h)^{n}-x^{n}}{h}$</p><p>$\\displaystyle =\\lim_{h \\to 0} \\dfrac{x^{n}+{}_{n}\\mathrm{C}_{1}x^{n-1}h+{}_{n}\\mathrm{C}_{2}x^{n-2}h^{2}+\\cdots+h^{n}-x^{n}}{h}$</p><p>$\\displaystyle =\\lim_{h \\to 0} \\left({}_{n}\\mathrm{C}_{1}x^{n-1}+{}_{n}\\mathrm{C}_{2}x^{n-2}h+\\cdots+h^{n-1}\\right)$</p><p>$={}_{n}\\mathrm{C}_{1}x^{n-1}$</p><p>$=\\boldsymbol{nx^{n-1}}$</p><p><b style=\"color: black\">別解</b></p><p>$f(x)=x^{n}$ とおくと</p><p>　$\\displaystyle \\lim_{h \\to 0} \\dfrac{(x+h)^{n}-x^{n}}{h}$</p><p>$=\\displaystyle \\lim_{h\\to 0}\\dfrac{f(x+h)-f(x)}{h}$</p><p>$=f'(x)$</p><p>$=\\boldsymbol{nx^{n-1}}$</p>",
    //導関数の定義，ごよ１１
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+1}+\\dfrac{1}{n+2}+\\cdots+\\dfrac{1}{4n}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+1}+\\dfrac{1}{n+2}+\\cdots+\\dfrac{1}{4n}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{3n}\\frac{1}{n+k}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\frac{1}{n}\\sum_{k=1}^{3n}\\frac{1}{1+\\dfrac{k}{n}}$</p><p>$\\displaystyle =\\int_{0}^{3}\\dfrac{1}{1+x}\\,dx$</p><p>$\\displaystyle =\\Bigl[\\log(1+x)\\Bigr]_{0}^{3}$</p><p>$\\displaystyle =\\boldsymbol{2\\log2}$</p>",
    // 区分求積，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sqrt[n]{(n+1)(n+2)\\cdots(2n)}}{n}$": "<p>$\\displaystyle A_{n}=\\dfrac{\\sqrt[n]{(n+1)(n+2)\\cdots(2n)}}{n}$ とおくと</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\log A_{n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\log \\sqrt[n]{\\left(1+\\dfrac{1}{n}\\right)\\left(1+\\dfrac{2}{n}\\right)\\cdots\\left(1+\\dfrac{n}{n}\\right)}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\log\\left(1+\\dfrac{1}{n}\\right)\\left(1+\\dfrac{2}{n}\\right)\\cdots\\left(1+\\dfrac{n}{n}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\left\\{\\log \\left(1+\\dfrac{1}{n}\\right)+\\log\\left(1+\\dfrac{2}{n}\\right)+\\cdots+\\log\\left(1+\\dfrac{n}{n}\\right)\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=1}^{n}\\log \\left(1+\\dfrac{k}{n}\\right)$</p><p>$\\displaystyle =\\int_{0}^{1}\\log(1+x)\\,dx$</p><p>$\\displaystyle =\\Bigl[(1+x)\\log(1+x)\\Bigr]_{0}^{1}-\\int_{0}^{1}(1+x)\\dfrac{1}{1+x}\\,dx$</p><p>$\\displaystyle =2\\log2-1$</p><p>$\\displaystyle =\\log\\dfrac{4}{e}$</p><p>　$\\displaystyle \\therefore \\lim_{n \\to \\infty}A_{n}=\\boldsymbol{\\dfrac{4}{e}}$</p>",
    // 区分求積log，サイトの練習
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{_{3n}{\\rm C}_{n}}{_{2n}{\\rm C}_{n}}\\right)^{\\frac{1}{n}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\log\\left(\\dfrac{_{3n}{\\rm C}_{n}}{_{2n}{\\rm C}_{n}}\\right)^{\\frac{1}{n}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\log\\left\\{\\dfrac{(3n)!}{n!(2n)!}\\cdot \\dfrac{n!n!}{(2n)!}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\log\\left\\{\\dfrac{(3n)!n!}{(2n)!(2n)!}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\log\\left\\{\\dfrac{(3n)(3n-1)\\cdots(3n-(n-1))}{(2n)(2n-1)\\cdots(2n-(n-1))}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\left(\\log\\dfrac{3n}{2n}+\\log\\dfrac{3n-1}{2n-1}+\\cdots+\\log\\dfrac{3n-(n-1)}{2n-(n-1)}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=0}^{n-1}\\log\\dfrac{3n-k}{2n-k}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=0}^{n-1}\\log\\dfrac{3-\\dfrac{k}{n}}{2-\\dfrac{k}{n}}$</p><p>$\\displaystyle =\\int_{0}^{1}\\log\\dfrac{3-x}{2-x}\\,dx$</p><p>$\\displaystyle =\\int_{0}^{1}\\log(3-x)\\,dx-\\int_{0}^{1}\\log(2-x)\\,dx$</p><p>$\\displaystyle =\\int_{3}^{2}\\log s (-1)\\,ds-\\int_{2}^{1}\\log t (-1)\\,dt$ $(s=3-x，t=2-x)$</p><p>$\\displaystyle =\\int_{2}^{3}\\log x\\,dx+\\int_{2}^{1}\\log x\\,dx$</p><p>$=f(3)+f(1)-2f(2)$ $(f(x)=x\\log x-x，f'(x)=\\log x)$</p><p>$=3\\log 3-3+0-1-2(2\\log 2-2)$</p><p>$=\\log \\dfrac{27}{16}$</p><p>$\\displaystyle \\therefore \\ \\lim_{n \\to \\infty}\\left(\\dfrac{_{3n}{\\rm C}_{n}}{_{2n}{\\rm C}_{n}}\\right)^{\\frac{1}{n}}=\\boldsymbol{\\dfrac{27}{16}}$</p>",
    // 区分求積log，1988東工大
    "$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{1}{n^{2}}\\left\\{\\sqrt{(2n)^{2}-1^{2}}+\\sqrt{(2n)^{2}-2^{2}}+\\cdots+\\sqrt{(2n)^{2}-(2n-1)^2}\\right\\}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{1}{n^{2}}\\left\\{\\sqrt{(2n)^{2}-1^{2}}+\\sqrt{(2n)^{2}-2^{2}}+\\cdots+\\sqrt{(2n)^{2}-(2n-1)^2}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{n^{2}}\\sum\\limits_{k=1}^{2n-1}\\sqrt{(2n)^{2}-k^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{n}\\sum\\limits_{k=1}^{2n-1}\\sqrt{\\dfrac{4n^{2}-k^{2}}{n^{2}}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{n}\\sum\\limits_{k=1}^{2n-1}\\sqrt{4-\\left(\\dfrac{k}{n}\\right)^{2}}$</p><p>$\\displaystyle =\\int_{0}^{2}\\sqrt{4-x^{2}}dx$</p><p>$\\displaystyle \\int_{0}^{2}\\sqrt{4-x^{2}}dx$ は、半径2の四分円の面積を表すから</p><p>（与式）$=\\dfrac{\\pi\\cdot2^{2}}{4}=\\boldsymbol{\\pi}$</p>",
    //区分求積，ごよ１４
    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=n+1}^{2n}\\dfrac{n}{k^{2}-2nk+2n^{2}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=n+1}^{2n}\\dfrac{n}{k^{2}-2nk+2n^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=n+1}^{2n}\\dfrac{1}{\\left(\\dfrac{k}{n}\\right)^{2}-2\\left(\\dfrac{k}{n}\\right)+2}$</p><p>$\\displaystyle =\\int_{1}^{2}\\dfrac{1}{x^{2}-2x+2}\\,dx$</p><p>$\\displaystyle =\\int_{1}^{2}\\dfrac{1}{(x-1)^{2}+1}\\,dx$</p><p>$\\displaystyle =\\int_{0}^{\\frac{\\pi}{4}}\\dfrac{1}{\\tan^{2}\\theta+1}\\cdot\\dfrac{1}{\\cos^{2}\\theta}\\,dt$　$(\\tan\\theta=x-1)$</p><p>$=\\boldsymbol{\\dfrac{\\pi}{4}}$</p><p><b style=\"color: black\">別解</b></p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=n+1}^{2n}\\dfrac{n}{k^{2}-2nk+2n^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=n+1}^{2n}\\dfrac{n}{(k-n)^{2}+n^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\dfrac{n}{k^{2}+n^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=1}^{n}\\dfrac{1}{\\left(\\dfrac{k}{n}\\right)^{2}+1}$</p><p>$\\displaystyle =\\int_{0}^{1}\\dfrac{1}{x^{2}+1}\\,dx$</p><p>$\\displaystyle =\\int_{0}^{\\frac{\\pi}{4}}\\dfrac{1}{\\tan^{2}\\theta+1}\\cdot\\dfrac{1}{\\cos^{2}\\theta}\\,dt$　$(\\tan\\theta=x)$</p><p>$=\\boldsymbol{\\dfrac{\\pi}{4}}$</p>",
    //区分求積1〜2の積分
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n^{5}}\\sum_{k=1}^{n}k(k+1)(k+2)(k+3)$": "<p>　$\\displaystyle \\sum_{k=1}^{n}k(k+1)(k+2)(k+3)$</p><p>$\\displaystyle =\\dfrac{1}{5}\\sum_{k=1}^{n}\\{k(k+1)(k+2)(k+3)(k+4)-(k-1)k(k+1)(k+2)(k+3)\\}$</p><p>$\\displaystyle =\\dfrac{1}{5}\\left\\{\\sum_{k=1}^{n}k(k+1)(k+2)(k+3)(k+4)-\\sum_{k=1}^{n}(k-1)k(k+1)(k+2)(k+3)\\right\\}$</p><p>$\\displaystyle =\\dfrac{1}{5}\\left\\{\\sum_{k=1}^{n}k(k+1)(k+2)(k+3)(k+4)-\\sum_{k=1}^{n-1}k(k+1)(k+2)(k+3)(k+4)\\right\\}$</p><p>$=\\dfrac{1}{5}n(n+1)(n+2)(n+3)(n+4)$</p><p>これより</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n^{5}}\\sum_{k=1}^{n}k(k+1)(k+2)(k+3)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{5}\\left(1+\\dfrac{1}{n}\\right)\\left(1+\\dfrac{2}{n}\\right)\\left(1+\\dfrac{3}{n}\\right)\\left(1+\\dfrac{4}{n}\\right)$</p><p>$=\\boldsymbol{\\dfrac{1}{5}}$</p><p><b style=\"color: black\">別解</b></p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n^{5}}\\sum_{k=1}^{n}k(k+1)(k+2)(k+3)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n^{5}}\\sum_{k=1}^{n}(k^{4}+6k^{3}+11k^{2}+6k)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\left\\{\\dfrac{1}{n}\\sum_{k=1}^{n}\\left(\\dfrac{k}{n}\\right)^{4}+\\dfrac{3}{2n}\\left(1+\\dfrac{1}{n}\\right)^{2}+\\dfrac{11}{6n^2}\\left(1+\\dfrac{1}{n}\\right)\\left(2+\\dfrac{1}{n}\\right)+\\dfrac{3}{n^3}\\left(1+\\dfrac{1}{n}\\right)\\right\\}$</p><p>$\\displaystyle =\\int_{0}^{1}x^{4}\\,dx$</p><p>$=\\boldsymbol{\\dfrac{1}{5}}$</p>",
    //連続自然数積の和，区分求積
    "$\\displaystyle \\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{1}{k^{3}+3k^{2}+2k}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{1}{k^{3}+3k^{2}+2k}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{1}{k(k+1)(k+2)}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{1}{2}\\left\\{\\dfrac{1}{k(k+1)}-\\dfrac{1}{(k+1)(k+2)}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{2}\\left\\{\\sum_{k=1}^{n}\\dfrac{1}{k(k+1)}-\\sum_{k=1}^{n}\\dfrac{1}{(k+1)(k+2)}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{2}\\left\\{\\sum_{k=1}^{n}\\dfrac{1}{k(k+1)}-\\sum_{k=2}^{n+1}\\dfrac{1}{k(k+1)}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{2}\\left\\{\\dfrac{1}{1\\cdot 2}-\\dfrac{1}{(n+1)(n+2)}\\right\\}$</p><p>$\\displaystyle =\\boldsymbol{\\dfrac{1}{4}}$</p>",
    //2023立教大，部分分数分解
    "$\\displaystyle \\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{k}{k^{4}+k^{2}+1}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{k}{k^{4}+k^{2}+1}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{k}{(k^{2}+1)^{2}-k^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{k}{(k^{2}+1-k)(k^{2}+1+k)}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{1}{2}\\left(\\dfrac{1}{k^{2}+1-k}-\\dfrac{1}{k^{2}+1+k}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{1}{2}\\left\\{\\dfrac{1}{(k-1)k+1}-\\dfrac{1}{k(k+1)+1}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{2}\\left\\{\\sum_{k=1}^{n}\\dfrac{1}{(k-1)k+1}-\\sum_{k=2}^{n+1}\\dfrac{1}{(k-1)k+1}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{2}\\left\\{1-\\dfrac{1}{n(n+1)+1}\\right\\}$</p><p>$=\\boldsymbol{\\dfrac{1}{2}}$</p>",
    //いつかの数検1級，部分分数分解
    "$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{n}{2^{n}}$": "<p>$~0 &lt \\dfrac{n}{2^{n}}$</p><p>　$=\\dfrac{n}{(1+1)^{n}}$</p><p>　$=\\dfrac{n}{\\sum\\limits_{k=0}^{n} {}_{n}\\mathrm{C}_{k}}$</p><p>　$&lt \\dfrac{n}{\\sum\\limits_{k=0}^{2} {}_{n}\\mathrm{C}_{k}}=\\dfrac{1}{\\dfrac{1}{n}+1+\\dfrac{n-1}{2}}$</p><p>$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{1}{\\dfrac{1}{n}+1+\\dfrac{n-1}{2}}=0$ より</p><p>$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{n}{2^{n}}=\\boldsymbol{0}$</p>",
    //関数間の比較，ごよ１
    "$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{1}{\\sqrt[3]{n^{2}}(\\sqrt[3]{n+1}-\\sqrt[3]{n})}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{1}{\\sqrt[3]{n^{2}}(\\sqrt[3]{n+1}-\\sqrt[3]{n})}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{n^\\frac{2}{3}\\left\\{(n+1)^\\frac{1}{3}-(n)^\\frac{1}{3}\\right\\}} \\cdot \\dfrac{(n+1)^{\\frac{2}{3}}+(n+1)^\\frac{1}{3}n^\\frac{1}{3}+n^\\frac{2}{3}}{(n+1)^{\\frac{2}{3}}+(n+1)^\\frac{1}{3}n^\\frac{1}{3}+n^\\frac{2}{3}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\left\\{\\left(1+\\dfrac{1}{n}\\right)^{\\frac{2}{3}}+\\left(1+\\dfrac{1}{n}\\right)^\\frac{1}{3}+1\\right\\}$</p><p>$=1+1+1$</p><p>$=\\boldsymbol{3}$</p>",
    //有理化，ごよ２
    "$\\displaystyle \\lim_{x \\to \\infty} \\left(\\sqrt[3]{x^{3}-x^{2}}-x\\right)$": "<p>　$\\displaystyle \\lim_{x \\to \\infty} \\left(\\sqrt[3]{x^{3}-x^{2}}-x\\right)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} \\dfrac{x^{3}-x^{2}-x^{3}}{\\sqrt[3]{(x^{3}-x^{2})^{2}}+x\\sqrt[3]{x^{3}-x^{2}}+x^{2}}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} \\dfrac{-1}{\\sqrt[3]{\\left(1-\\dfrac{1}{x}\\right)^{2}}+\\sqrt[3]{1-\\dfrac{1}{x}}+1}$</p><p>$=\\boldsymbol{-\\dfrac{1}{3}}$</p>",
    //有理化，斜め漸近線が自身と交わる
    "$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{\\sin ^{n}\\theta - \\cos ^{n}\\theta}{\\sin ^{n}\\theta + \\cos ^{n}\\theta}　\\left(0 &lt \\theta &lt \\dfrac{\\pi}{2}\\right)$": "<p>$\\dfrac{\\sin ^{n}\\theta - \\cos ^{n}\\theta}{\\sin ^{n}\\theta + \\cos ^{n}\\theta}=\\dfrac{\\left(\\dfrac{\\sin \\theta}{\\cos \\theta}\\right)^{n} - 1}{\\left(\\dfrac{\\sin \\theta}{\\cos \\theta}\\right)^{n} + 1}=\\dfrac{\\tan ^{n}\\theta - 1}{\\tan ^{n}\\theta + 1}=\\dfrac{1-\\dfrac{1}{\\tan ^{n}\\theta}}{1+\\dfrac{1}{\\tan ^{n}\\theta}}$</p><p>(i) $ 0 &lt \\theta &lt \\dfrac{\\pi}{4} $ のとき</p><p>　　$0 &lt \\tan \\theta &lt 1$ だから</p><p>　（与式）$= \\displaystyle \\lim_{n \\to \\infty} \\dfrac{\\tan ^{n}\\theta - 1}{\\tan ^{n}\\theta + 1}=\\dfrac{0-1}{0+1}=-1$</p><p>(ii) $ \\theta=\\dfrac{\\pi}{4} $ のとき</p><p>　　$\\tan \\theta =1$ だから</p><p>　（与式）$= \\displaystyle \\lim_{n \\to \\infty} \\dfrac{\\tan ^{n}\\theta - 1}{\\tan ^{n}\\theta + 1}=\\dfrac{1-1}{1+1}=0$</p><p>(iii) $ \\dfrac{\\pi}{4} &lt \\theta &lt \\dfrac{\\pi}{2} $ のとき</p><p>　　$\\tan \\theta &gt 1$ だから</p><p>　（与式）$= \\displaystyle \\lim_{n \\to \\infty}  =\\dfrac{1-\\dfrac{1}{\\tan ^{n}\\theta}}{1+\\dfrac{1}{\\tan ^{n}\\theta}}=\\dfrac{1-0}{1+0}=1$</p><p>以上より</p><p style=\"text-align: center\">（与式）$=\\begin{cases} \\boldsymbol{-1 \\ \\ \\ \\left(0 &lt \\theta &lt \\dfrac{\\pi}{4}\\right)} \\\\ \\boldsymbol{0 \\ \\ \\ \\left(\\theta = \\dfrac{\\pi}{4}\\right)} \\\\ \\boldsymbol{1 \\ \\ \\ \\left(\\dfrac{\\pi}{4} &lt \\theta &lt \\dfrac{\\pi}{2}\\right)}\\end{cases}$</p>",
    //三角関数と等比場合分け，ごよ３
    "$\\displaystyle \\lim_{n \\to \\infty} \\dfrac{x^{n-1} - 3^{n+1}}{x^{n} + 3^{n-1}}$　$( \\ x &gt 0 \\ )$": "<p>$f(x)=\\dfrac{x^{n-1}-3^{n+1}}{x^{n}+3^{n-1}}$ とする</p><p>(i) $ 0 &lt x &lt 3 $ のとき</p><p>　　$\\displaystyle \\lim_{n \\to \\infty} f(x)$</p><p>　$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{\\dfrac{1}{3}\\left(\\dfrac{x}{3}\\right)^{n-1}-3}{\\left(\\dfrac{x}{3}\\right)^{n}+\\dfrac{1}{3}}$</p><p>　$\\displaystyle =\\dfrac{\\dfrac{1}{3} \\cdot 0-3}{0+\\dfrac{1}{3}}$</p><p>　$=-9$</p><p>(ii) $ x=3 $ のとき</p><p>　　$\\displaystyle \\lim_{n \\to \\infty} f(x)$</p><p>　$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{3^{n-1} - 3^{n+1}}{3^{n} + 3^{n-1}}　(x &gt 0)$</p><p>　$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{-8 \\cdot 3^{n-1}}{4 \\cdot 3^{n-1}}$</p><p>　$=-2$</p><p>(iii) $ 3 &lt x $ のとき</p><p>　　$\\displaystyle \\lim_{n \\to \\infty} f(x)$</p><p>　$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1-9\\left(\\dfrac{3}{x}\\right)^{n-1}}{x+\\left(\\dfrac{3}{x}\\right)^{n-1}}$</p><p>　$=\\dfrac{1-9 \\cdot 0}{x+0}$</p><p>　$=\\dfrac{1}{x}$</p><p>以上より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty} f(x)=\\begin{cases} \\boldsymbol{-9 \\ \\ \\ (0 &lt x &lt 3)} \\\\ \\boldsymbol{-2 \\ \\ \\ (x=3)} \\\\ \\boldsymbol{\\dfrac{1}{x} \\ \\ \\ (3 &lt x)}\\end{cases}$</p>",
    //等比場合分け，ごよ４
    "$\\displaystyle \\lim_{n \\to \\infty} \\sum\\limits_{k=1}^{n} k\\left(\\dfrac{1}{2}\\right)^{k-1}$　$\\displaystyle  \\left(\\lim_{n \\to \\infty} n\\left(\\dfrac{1}{2}\\right)^{n-1}=0\\right)$": "<p>$\\displaystyle S_{n}=\\sum_{k=1}^{n} k\\left(\\dfrac{1}{2}\\right)^{k-1}=1+2 \\cdot \\dfrac{1}{2}+ \\cdots +n\\left(\\dfrac{1}{2}\\right)^{n-1}$ とおく</p><p>\\begin{alignat}{2}S_{n} &= & ~1+2 \\cdot \\dfrac{1}{2} &+ & ~3\\left(\\dfrac{1}{2}\\right)^{2}+ \\cdots +n\\left(\\dfrac{1}{2}\\right)^{n-1} \\cdots ①　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\\\\[6pt]\\dfrac{S_{n}}{2} &= & \\dfrac{1}{2} &+ & ~2\\left(\\dfrac{1}{2}\\right)^{2}+ \\cdots +(n-1)\\left(\\dfrac{1}{2}\\right)^{n-1}+n\\left(\\dfrac{1}{2}\\right)^{n} \\cdots ②\\end{alignat}</p><p>①$-$②より</p><p>\\begin{align}\\dfrac{S_{n}}{2}&=1+\\dfrac{1}{2}+\\left(\\dfrac{1}{2}\\right)^{2}+ \\cdots +\\left(\\dfrac{1}{2}\\right)^{n-1}-n\\left(\\dfrac{1}{2}\\right)^{n}　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\\\\[6pt]&=\\dfrac{1-\\left(\\dfrac{1}{2}\\right)^{n}}{1-\\dfrac{1}{2}}-n\\left(\\dfrac{1}{2}\\right)^{n} \\\\[6pt]&=2-\\left(\\dfrac{1}{2}\\right)^{n-1}-n\\left(\\dfrac{1}{2}\\right)^{n}\\end{align}</p><p>よって　$S_{n}=4-\\left(\\dfrac{1}{2}\\right)^{n-2}-n\\left(\\dfrac{1}{2}\\right)^{n-1}$</p><p>$\\displaystyle \\lim_{n \\to \\infty} \\left(\\dfrac{1}{2}\\right)^{n-2}=0,　\\lim_{n \\to \\infty} n\\left(\\dfrac{1}{2}\\right)^{n-1}=0$ だから</p><p>$\\displaystyle \\lim_{n \\to \\infty} S_{n}=\\boldsymbol{4}$</p>",
    //等差×等比，ごよ５
    "$\\displaystyle \\lim_{n \\to \\infty} \\sum\\limits_{k=0}^{n} \\left(\\dfrac{1}{5^{k}}\\cos k\\pi+\\dfrac{1}{3^{\\frac{k}{2}}}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\sum\\limits_{k=0}^{n} \\left(\\dfrac{1}{5^{k}}\\cos k\\pi+\\dfrac{1}{3^{\\frac{k}{2}}}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\sum\\limits_{k=0}^{n} \\left\\{\\dfrac{1}{5^{k}}\\cdot (-1)^{k}+\\left(\\dfrac{1}{\\sqrt{3}}\\right)^{k}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\sum\\limits_{k=0}^{n} \\left\\{\\left(-\\dfrac{1}{5}\\right)^{k}+\\left(\\dfrac{1}{\\sqrt{3}}\\right)^{k}\\right\\}$</p><p>$=\\dfrac{1}{1+\\dfrac{1}{5}}+\\dfrac{1}{1-\\dfrac{1}{\\sqrt{3}}}$</p><p>$=\\boldsymbol{\\dfrac{14+3\\sqrt{3}}{6}}$</p>",
    //等比級数，ごよ６
    "$\\displaystyle \\lim_{x \\to \\infty} \\left(3^{x}+5^{x}\\right)^{\\frac{1}{x}}$": "<p>$\\left(3^{x}+5^{x}\\right)^{\\frac{1}{x}}=\\left\\lbrack 5^{x} \\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\} \\right\\rbrack^{\\frac{1}{x}}=5\\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\}^{\\frac{1}{x}}$</p><p>$x \\to \\infty$ だから，$x &gt 1，0 &lt \\dfrac{1}{x} &lt 1$ と考えてよい</p><p>このとき</p><p>$\\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\}^{0} &lt \\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\}^{\\frac{1}{x}} &lt \\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\}^{1}$</p><p>$1 &lt \\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\}^{\\frac{1}{x}} &lt \\left(\\dfrac{3}{5}\\right)^{x}+1$</p><p>$\\displaystyle \\lim_{x \\to \\infty} \\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\}=1$ だから</p><p>$\\displaystyle \\lim_{x \\to \\infty} \\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\}^{\\frac{1}{x}}=1$</p><p>よって　$\\displaystyle \\lim_{x \\to \\infty} \\left(3^{x}+5^{x}\\right)^{\\frac{1}{x}}=\\lim_{x \\to \\infty} 5\\left\\{\\left(\\dfrac{3}{5}\\right)^{x}+1\\right\\}^{\\frac{1}{x}}=\\boldsymbol{5}$</p>",
    //はさみうち，ごよ８
    "$\\displaystyle \\lim_{x \\to 0} \\dfrac{\\sqrt{\\cos 4x}-\\sqrt{\\cos 2x}}{x^{2}}$": "<p>　$\\displaystyle \\lim_{x \\to 0} \\dfrac{\\sqrt{\\cos 4x}-\\sqrt{\\cos 2x}}{x^{2}}$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\dfrac{\\cos 4x-\\cos 2x}{x^{2}(\\sqrt{\\cos 4x}+\\sqrt{\\cos 2x})}$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\dfrac{-2\\sin 3x \\sin x}{x^{2}(\\sqrt{\\cos 4x}+\\sqrt{\\cos 2x})}$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\dfrac{\\sin 3x}{3x} \\cdot \\dfrac{\\sin x}{x} \\cdot \\dfrac{-6}{\\sqrt{\\cos 4x}+\\sqrt{\\cos 2x}}$</p><p>$=1 \\cdot 1 \\cdot \\dfrac{-6}{2}$</p><p>$=\\boldsymbol{-3}$</p>",
    //三角関数と有理化，ごよ９
    "$\\displaystyle \\lim_{x \\to \\frac{1}{4}} \\dfrac{\\tan \\pi x-1}{4x-1}$": "<p>　$\\displaystyle \\lim_{x \\to \\frac{1}{4}} \\dfrac{\\tan \\pi x-1}{4x-1}$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{\\tan \\left(\\pi t+\\dfrac{\\pi}{4}\\right)-1}{4t}$　$\\left(t=x-\\dfrac{1}{4}\\right)$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{\\dfrac{\\tan \\pi t+1}{1-\\tan \\pi t}-1}{4t}$</p> <p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{\\tan \\pi t}{2t(1-\\tan \\pi t)}$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{\\sin \\pi t}{2t(\\cos \\pi t-\\sin \\pi t)}$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{\\sin \\pi t}{\\pi t} \\cdot \\dfrac{\\pi}{2} \\cdot \\dfrac{1}{\\cos \\pi t-\\sin \\pi t}$</p><p>$=1 \\cdot \\dfrac{\\pi}{2} \\cdot \\dfrac{1}{1-0}$</p><p>$=\\boldsymbol{\\dfrac{\\pi}{2}}$</p>",
    //三角関数，ごよ１２
    "$\\displaystyle \\lim_{x \\to \\infty} x\\sin (\\sqrt{a^{2}x^{2}+b}-ax)$　$( \\ a，b \\ は正の実数 \\ )$": "<p>　$\\displaystyle \\lim_{x \\to \\infty} x\\sin (\\sqrt{a^{2}x^{2}+b}-ax)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} x\\sin \\dfrac{b}{\\sqrt{a^{2}x^{2}+b}+ax}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} \\dfrac{\\sin \\dfrac{b}{\\sqrt{a^{2}x^{2}+b}+ax}}{\\dfrac{b}{\\sqrt{a^{2}x^{2}+b}+ax}}\\cdot \\dfrac{bx}{\\sqrt{a^{2}x^{2}+b}+ax}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} \\dfrac{\\sin \\dfrac{b}{\\sqrt{a^{2}x^{2}+b}+ax}}{\\dfrac{b}{\\sqrt{a^{2}x^{2}+b}+ax}}\\cdot \\dfrac{b}{\\sqrt{a^{2}+\\dfrac{b}{x^{2}}}+a}$</p><p>$\\displaystyle =1\\cdot \\dfrac{b}{a+a}$　$\\left( \\ x \\to \\infty \\ のとき \\ \\dfrac{b}{\\sqrt{a^{2}x^{2}+b}+ax} \\to +0 \\ \\right)$</p><p>$=\\boldsymbol{\\dfrac{b}{2a}}$</p>",
    //三角関数，ごよ１３
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(1+2+3+\\cdots+n)^{5}}{(1^{4}+2^{4}+3^{4}+\\cdots+n^{4})^{2}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(1+2+3+\\cdots+n)^{5}}{(1^{4}+2^{4}+3^{4}+\\cdots+n^{4})^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\left(\\sum\\limits_{k=1}^{n}k\\right)^{5}}{\\left(\\sum\\limits_{k=1}^{n}k^{4}\\right)^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\dfrac{1}{n^{10}}\\left\\{\\dfrac{1}{2}n(n+1)\\right\\}^{5}}{\\dfrac{1}{n^{10}}\\left(\\sum\\limits_{k=1}^{n}k^{4}\\right)^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\left\\{\\dfrac{1}{2}\\cdot 1\\cdot\\left(1+\\dfrac{1}{n}\\right)\\right\\}^{5}}{\\left\\{\\dfrac{1}{n}\\sum\\limits_{k=1}^{n}\\left(\\dfrac{k}{n}\\right)^{4}\\right\\}^{2}}$</p><p>$=\\dfrac{\\dfrac{1}{32}}{\\displaystyle \\left(\\int_{0}^{1}x^{4}\\,dx\\right)^{2}}$</p><p>$=\\boldsymbol{\\dfrac{25}{32}}$</p>",
    //区分求積の基本，Σk^4
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+1)^{k}+(n+2)^{k}+\\cdots+(n+2n)^{k}}{1^{k}+2^{k}+\\cdots+(2n)^{k}}$ $( \\ k \\ は実数 \\ )$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+1)^{k}+(n+2)^{k}+\\cdots+(n+2n)^{k}}{1^{k}+2^{k}+\\cdots+(2n)^{k}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\displaystyle \\sum_{i=1}^{2n}(n+i)^{k}}{\\displaystyle \\sum_{i=1}^{2n}i^{k}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\displaystyle \\dfrac{1}{n}\\sum_{i=1}^{2n}\\left(1+\\dfrac{i}{n}\\right)^{k}}{\\displaystyle \\dfrac{1}{n}\\sum_{i=1}^{2n}\\left(\\dfrac{i}{n}\\right)^{k}}$</p><p>$=\\dfrac{\\displaystyle \\int_{0}^{2}(1+x)^{k}\\,dx}{\\displaystyle \\int_{0}^{2}x^{k}\\,dx}$</p><p>$=\\dfrac{\\left[\\dfrac{1}{k+1}(1+x)^{k+1}\\right]_{0}^{2}}{\\left[\\dfrac{1}{k+1}x^{k+1}\\right]_{0}^{2}}$</p><p>$=\\dfrac{\\dfrac{1}{k+1}(3^{k+1}-1)}{\\dfrac{2^{k+1}}{k+1}}$</p><p>$=\\boldsymbol{\\dfrac{3^{k+1}-1}{2^{k+1}}}$</p>",
    //区分求積，Z会
    "$\\displaystyle \\lim_{t \\to 0}\\dfrac{1}{t}\\left(\\dfrac{1}{\\left|\\overrightarrow{\\mathstrut a}-t\\overrightarrow{\\mathstrut b}\\right|}-\\dfrac{1}{\\left|\\overrightarrow{\\mathstrut a}+t\\overrightarrow{\\mathstrut b}\\right|}\\right)$　$\\left(\\overrightarrow{\\mathstrut a}=(3,4)，\\overrightarrow{\\mathstrut b}=(1,2)\\right)$": "<p>$f(t)=\\dfrac{1}{t}\\left(\\dfrac{1}{\\left|\\overrightarrow{\\mathstrut a}-t\\overrightarrow{\\mathstrut b}\\right|}-\\dfrac{1}{\\left|\\overrightarrow{\\mathstrut a}+t\\overrightarrow{\\mathstrut b}\\right|}\\right)$ とおく．</p><p>$\\overrightarrow{\\mathstrut a}-t\\overrightarrow{\\mathstrut b}=(3-t,4-2t)$，$\\overrightarrow{\\mathstrut a}+t\\overrightarrow{\\mathstrut b}=(3+t,4+2t)$ より</p><p>　$f(t)$</p><p>$=\\dfrac{1}{t}\\left(\\dfrac{1}{\\sqrt{(3-t)^{2}+(4-2t)^{2}}}-\\dfrac{1}{\\sqrt{(3+t)^{2}+(4+2t)^{2}}}\\right)$</p><p>$=\\dfrac{\\dfrac{1}{\\sqrt{5t^{2}-22t+25}}-\\dfrac{1}{\\sqrt{5t^{2}+22t+25}}}{t}$</p><p>$=\\dfrac{\\sqrt{T+22t}-\\sqrt{T-22t}}{t\\sqrt{T-22t}\\sqrt{T+22t}}$　$(T=5t^{2}+25)$</p><p>$=\\dfrac{44t}{t\\sqrt{T-22t}\\sqrt{T+22t}(\\sqrt{T+22t}+\\sqrt{T-22t})}$</p><p>$=\\dfrac{44}{\\sqrt{5t^{2}+25-22t}\\sqrt{5t^{2}+25+22t}(\\sqrt{5t^{2}+25+22t}+\\sqrt{5t^{2}+25-22t})}$</p><p>　$\\displaystyle \\therefore \\ \\lim_{t \\to 0}f(t)=\\dfrac{44}{5\\cdot5(5+5)}=\\boldsymbol{\\dfrac{22}{125}}$</p><p><b style=\"color: black\">別解</b></p><p>　$f(t)$</p><p>$=\\dfrac{\\dfrac{1}{\\sqrt{5t^{2}-22t+25}}-\\dfrac{1}{\\sqrt{5t^{2}+22t+25}}}{t}$</p><p>$=\\dfrac{g(t)-g(0)-(h(t)-h(0))}{t}$　$\\left(g(t)=\\dfrac{1}{\\sqrt{5t^{2}-22t+25}}，h(t)=\\dfrac{1}{\\sqrt{5t^{2}+22t+25}}\\right)$</p><p>$=\\dfrac{g(t)-g(0)}{t-0}-\\dfrac{h(t)-h(0)}{t-0}$</p><p>　$\\displaystyle \\lim_{t \\to 0}f(t)$</p><p>$=g'(0)-h'(0)$</p><p>$=\\dfrac{11}{125}-\\dfrac{-11}{125}$　$\\left(g'(t)=-\\dfrac{1}{2}(5t^{2}-22t+25)^{-\\frac{3}{2}}(10t-22)，h'(t)=-\\dfrac{1}{2}(5t^{2}+22t+25)^{-\\frac{3}{2}}(10t+22)\\right)$</p><p>$=\\boldsymbol{\\dfrac{22}{125}}$</p>",
    //2017東京医科大
    "$\\displaystyle \\lim_{n \\to \\infty}\\int_{0}^{n}e^{-t}\\cos(tx)\\,dt$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\int_{0}^{n}e^{-t}\\cos(tx)\\,dt$</p><p>$\\displaystyle I_{n}=\\int_{0}^{n}e^{-t}\\cos(tx)\\,dt$ とおく．</p><p>　$\\displaystyle I_{n}$</p><p>$\\displaystyle =\\Bigl[-e^{-t}\\cos(tx)\\Bigr]_{0}^{n}-\\int_{0}^{n}(-e^{-t})(-x\\sin(tx))\\,dt$</p><p>$\\displaystyle =-e^{-n}\\cos(nx)+1-x\\int_{0}^{n}e^{-t}\\sin(tx)\\,dt$</p><p>$\\displaystyle =-e^{-n}\\cos(nx)+1-x\\left(\\Bigl[-e^{-t}\\sin(tx)\\Bigr]_{0}^{n}-\\int_{0}^{n}(-e^{-t})x\\cos(tx)\\,dt\\right)$</p><p>$\\displaystyle =-e^{-n}\\cos(nx)+1+xe^{-n}\\sin(nx)-x^{2}I_{n}$</p><p>これより</p><p style=\"text-align: center\">$\\displaystyle (x^{2}+1)I_{n}=-e^{-n}\\cos(nx)+xe^{-n}\\sin(nx)+1$</p><p style=\"text-align: center\">$\\displaystyle \\therefore \\ I_{n}=\\dfrac{1}{x^{2}+1}\\{-e^{-n}\\cos(nx)+xe^{-n}\\sin(nx)+1\\}$</p><p>ここで，$-1\\leqq \\cos(nx)\\leqq 1$，$-1\\leqq \\sin(nx)\\leqq 1$ より</p><p style=\"text-align: center\">$-e^{-n}\\leqq e^{-n}\\cos(nx)\\leqq e^{-n}$，$-e^{-n}\\leqq e^{-n}\\sin(nx)\\leqq e^{-n}$</p><p>ここで，$\\displaystyle \\lim_{n \\to \\infty}(-e^{-n})=\\lim_{n \\to \\infty}e^{-n}=0$ より，$\\displaystyle \\lim_{n \\to \\infty}e^{-n}\\cos(nx)=\\lim_{n \\to \\infty}e^{-n}\\sin(nx)=0$．</p><p style=\"text-align: center\">$\\displaystyle \\therefore \\ \\lim_{n \\to \\infty}I_{n}=\\boldsymbol{\\dfrac{1}{x^{2}+1}}$</p>",
    //2023浜松医科大
    "$\\displaystyle \\lim_{x \\to k-0} ([3x]-3[x])$　$( \\ k \\ は整数 \\ )$": "<p>$x \\to k-0$ を考えるから $k-\\dfrac{1}{3} &lt x &lt k$ としてよい．</p><p>このとき $[x]=k-1$．</p><p>また $3k-1 &lt 3x &lt 3k$ だから $[3x]=3k-1$．</p><p>よって $\\displaystyle \\lim_{x \\to k-0} ([3x]-3[x])=3k-1-3(k-1)=\\boldsymbol{2}$</p>",
    //ガウス，ごよ１０
        },
        "C": {
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+\\dfrac{1}{2}}+\\dfrac{1}{n+\\dfrac{3}{2}}+\\dfrac{1}{n+\\dfrac{5}{2}}+\\cdots+\\dfrac{2}{6n-1}\\right)$":
    // 区分求積(奇数番目の和)，サイトの練習
    "<p>　$\\displaystyle\\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+\\dfrac{1}{2}}+\\dfrac{1}{n+\\dfrac{3}{2}}+\\dfrac{1}{n+\\dfrac{5}{2}}+\\cdots+\\dfrac{1}{3n-\\dfrac{1}{2}}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{2n}\\dfrac{1}{n+\\dfrac{2k-1}{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{2n}\\dfrac{1}{1+\\dfrac{2k-1}{2n}}\\cdot\\dfrac{1}{n}$</p><p>$\\displaystyle =\\int_{0}^{2}\\dfrac{1}{1+x}\\,dx$</p><p>$\\displaystyle =\\boldsymbol{\\log3}$</p><p><b style=\"color: black\">別解</b></p><p>　$\\displaystyle\\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+\\dfrac{1}{2}}+\\dfrac{1}{n+\\dfrac{3}{2}}+\\dfrac{1}{n+\\dfrac{5}{2}}+\\cdots+\\dfrac{1}{3n-\\dfrac{1}{2}}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+\\dfrac{1}{2}}+\\dfrac{1}{n+\\dfrac{3}{2}}+\\dfrac{1}{n+\\dfrac{5}{2}}+\\cdots+\\dfrac{1}{n+\\dfrac{4n-1}{2}}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\left(\\sum_{k=1}^{4n}\\dfrac{1}{n+\\dfrac{k}{2}}-\\sum_{k=1}^{2n}\\dfrac{1}{n+\\dfrac{2k}{2}}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\frac{1}{n}\\left(\\sum_{k=1}^{4n}\\dfrac{1}{1+\\dfrac{1}{2}\\dfrac{k}{n}}-\\sum_{k=1}^{2n}\\dfrac{1}{1+\\dfrac{k}{n}}\\right)$</p><p>$\\displaystyle =\\int_{0}^{4}\\dfrac{1}{1+\\dfrac{1}{2}x}\\,dx-\\int_{0}^{2}\\dfrac{1}{1+x}\\,dx$</p><p>$\\displaystyle =\\left[2\\log\\left(1+\\dfrac{1}{2}x\\right)\\right]_{0}^{4}-\\Bigl[\\log\\left(1+x\\right)\\Bigr]_{0}^{2}$</p><p>$\\displaystyle =2\\log3-\\log3$</p><p>$\\displaystyle =\\boldsymbol{\\log3}$</p>",
    

    "$\\displaystyle \\lim_{x \\to \\infty}\\dfrac{x}{e^{x}}$":
    // x/e^{x}の極限
    "<p>$f(x)=e^{x}-1-x-\\dfrac{x^{2}}{2}$ $(x&gt;0)$ とおく．</p><p>$f'(x)=e^{x}-1-x$</p><p>$f''(x)=e^{x}-1&gt;0$ $(x&gt;0)$ </p><p>これより $f'(x)$ は単調増加．$f'(0)=0$ より $f'(x)&gt;0$．</p><p>これより $f(x)$ は単調増加．$f(0)=0$ より $f(x)&gt;0$．</p><p style=\"text-align: center\">$\\therefore \\ e^{x}&gt;1+x+\\dfrac{x^{2}}{2}$ $(x&gt;0)$</p><p>両辺 $x$ で割って逆数とると</p><p style=\"text-align: center\">$0&lt;\\dfrac{x}{e^{x}}&lt;\\dfrac{1}{\\dfrac{1}{x}+1+\\dfrac{x}{2}}$ $(x&gt;0)$</p><p>$\\displaystyle \\lim_{x \\to \\infty}\\dfrac{1}{\\dfrac{1}{x}+1+\\dfrac{x}{2}}=0$ より $\\displaystyle \\lim_{x \\to \\infty}\\dfrac{x}{e^{x}}=\\boldsymbol{0}$</p>",


    "$\\displaystyle \\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{1}{k}$":
    // 調和級数，面積評価
    "<p>$0&lt;k\\leqq x \\leqq k+1$ において，$y=\\dfrac{1}{x}$ は単調減少より</p><p style=\"text-align: center\">$\\displaystyle \\dfrac{1}{x}\\leqq \\dfrac{1}{k}$</p><p>$k\\leqq x \\leqq k+1$ において両辺積分すると</p><p style=\"text-align: center\">$\\displaystyle \\int_{k}^{k+1}\\dfrac{1}{x}\\,dx&lt; \\int_{k}^{k+1}\\dfrac{1}{k}\\,dx=\\dfrac{1}{k}$</p><p>$k=1,2,\\cdots,n$ で辺々足していくと</p><p style=\"text-align: center\">$\\displaystyle \\int_{1}^{n+1}\\dfrac{1}{x}\\,dx&lt; \\sum_{k=1}^{n}\\dfrac{1}{k}$</p><p>左辺を計算して</p><p style=\"text-align: center\">$\\displaystyle \\log(n+1)&lt; \\sum_{k=1}^{n}\\dfrac{1}{k}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\log(n+1)=\\infty$ より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty} \\sum_{k=1}^{n}\\dfrac{1}{k}=\\boldsymbol{\\infty}$</p>",


    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{n!}{2^n}$":
    // 階乗と指数関数の比較
    "<p>$n\\geqq 5$ のとき</p><p>　$\\dfrac{n!}{2^{n}}$</p><p>$=\\dfrac{1}{2}\\cdot\\dfrac{2}{2}\\cdot\\dfrac{3}{2}\\cdot\\dfrac{4}{2}\\cdot\\dfrac{5}{2}\\cdots\\dfrac{n}{2}$</p><p>$&gt;1\\cdot\\dfrac{5}{2}\\cdot\\dfrac{6}{2}\\cdots\\dfrac{n}{2}$</p><p>$\\geqq \\dfrac{n}{2}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{n}{2}=\\infty$ より，$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{n!}{2^{n}}=\\boldsymbol{\\infty}$</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\log (n!)}{n\\log n}$":
    // 面積評価
    "<p>$y=\\log x$ は単調増加なので，$k \\leqq x \\leqq k+1 \\ \\Longleftrightarrow \\ x-1 \\leqq k \\leqq x$ において</p><p style=\"text-align: center\">$\\log(x-1) \\leqq \\log k \\leqq \\log x$</p><p>すべての辺で，$k \\leqq x \\leqq k+1$ で積分すると</p><p style=\"text-align: center\">$\\displaystyle \\int_{k}^{k+1}\\log(x-1)\\,dx \\leqq \\int_{k}^{k+1}\\log k\\,dx \\leqq \\int_{k}^{k+1}\\log x\\,dx$</p><p>が成り立つ．$\\displaystyle \\int_{k}^{k+1}\\log k\\,dx=\\log k$ より</p><p style=\"text-align: center\">$\\begin{cases}\\displaystyle \\int_{k}^{k+1}\\log(x-1)\\,dx \\leqq \\log k \\ \\cdots ① \\\\ \\displaystyle \\log k \\leqq \\int_{k}^{k+1}\\log x\\,dx  \\ \\cdots ②\\end{cases}$</p><p>①で $k=2,3,\\cdots,n$ ( $n\\geqq 2$ )で両辺足していくと</p><p style=\"text-align: center\">$\\displaystyle \\int_{2}^{n+1}\\log(x-1)\\,dx \\leqq \\sum_{k=2}^{n}\\log k$</p><p style=\"text-align: center\">$\\displaystyle \\Longleftrightarrow \\ \\int_{1}^{n}\\log t\\,dt \\leqq \\sum_{k=1}^{n}\\log k$　( $t=x-1$ )</p><p style=\"text-align: center\">$\\displaystyle \\therefore \\ n\\log n-n+1 \\leqq \\log (n!) \\ \\cdots$ ③</p><p>②で $k=1,2,\\cdots,n-1$ ( $n\\geqq 2$ )で両辺足していくと</p><p style=\"text-align: center\">$\\displaystyle \\sum_{k=1}^{n-1}\\log k \\leqq \\int_{1}^{n}\\log x\\,dx=n\\log n-n+1$</p><p>両辺 $\\log n$ 足すと</p><p style=\"text-align: center\">$\\displaystyle \\sum_{k=1}^{n}\\log k=\\log(n!) \\leqq n\\log n-n+1+\\log n \\ \\cdots$ ④</p><p>③，④より，$n\\geqq 2$ において</p><p style=\"text-align: center\">$n\\log n-n+1 \\leqq \\log(n!) \\leqq n\\log n-n+1+\\log n$</p><p>両辺 $n\\log n$ で割ると</p><p style=\"text-align: center\">$1-\\dfrac{1}{\\log n}+\\dfrac{1}{n\\log n} \\leqq \\dfrac{\\log (n!)}{n\\log n} \\leqq 1-\\dfrac{1}{\\log n}+\\dfrac{1}{n\\log n}+\\dfrac{1}{n}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\left(1-\\dfrac{1}{\\log n}+\\dfrac{1}{n\\log n}\\right)=\\lim_{n \\to \\infty}\\left(1-\\dfrac{1}{\\log n}+\\dfrac{1}{n\\log n}+\\dfrac{1}{n}\\right)=1$ より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\log (n!)}{n\\log n}=\\boldsymbol{1}$</p>",
    

    "$\\displaystyle \\lim_{x \\to \\infty}\\left\\{\\dfrac{2x-2}{2x-1}-\\dfrac{2}{(2x-1)^{2}}\\right\\}^{2x}$":
    // eの極限，2016防衛医大
    "<p>　$\\displaystyle \\lim_{x \\to \\infty}\\left\\{\\dfrac{2x-2}{2x-1}-\\dfrac{2}{(2x-1)^{2}}\\right\\}^{2x}$ </p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\left(\\dfrac{t-1}{t}-\\dfrac{2}{t^{2}}\\right)^{t+1}$　$(t=2x-1)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\left(\\dfrac{t^{2}-t-2}{t^{2}}\\right)^{t+1}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\left(\\dfrac{t-2}{t}\\right)^{t+1}\\left(\\dfrac{t+1}{t}\\right)^{t+1}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\left(1+\\dfrac{-2}{t}\\right)^{t}\\left(1+\\dfrac{-2}{t}\\right)\\left(1+\\dfrac{1}{t}\\right)^{t}\\left(1+\\dfrac{1}{t}\\right)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\left\\{\\left(1+\\dfrac{-2}{t}\\right)^{\\frac{1}{\\frac{-2}{t}}}\\right\\}^{-2}\\left(1+\\dfrac{-2}{t}\\right)\\left(1+\\dfrac{1}{t}\\right)^{t}\\left(1+\\dfrac{1}{t}\\right)$</p><p>$=e^{-2}\\cdot1\\cdot e\\cdot1$</p><p>$=\\boldsymbol{\\dfrac{1}{e}}$</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\left(1+a^{n}\\right)^{\\frac{1}{n}}$　$( \\ a \\ は正の実数)$":
    // eの極限，2012京都大
    "<p>(ⅰ) $a=1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(1+a^{n}\\right)^{\\frac{1}{n}}=\\lim_{n \\to \\infty}2^{\\frac{1}{n}}=1$</p><p>(ⅱ) $0&lt;a&lt;1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(1+a^{n}\\right)^{\\frac{1}{n}}=\\left\\{\\left(1+a^{n}\\right)^{\\frac{1}{a^n}}\\right\\}^{\\frac{a^n}{n}}=e^{0}=1$</p><p>(ⅲ) $a&gt;1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\log\\left(1+a^{n}\\right)^{\\frac{1}{n}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\log \\left\\{a^{n}\\left(\\dfrac{1}{a^{n}}+1\\right)\\right\\}^{\\frac{1}{n}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\left\\{\\log a+\\dfrac{1}{n}\\log \\left(\\dfrac{1}{a^{n}}+1\\right)\\right\\}$</p><p>$=\\log a$</p><p>　$\\displaystyle \\therefore \\ \\lim_{n \\to \\infty}\\left(1+a^{n}\\right)^{\\frac{1}{n}}=a$</p><p>以上より</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(1+a^{n}\\right)^{\\frac{1}{n}}=\\begin{cases}\\boldsymbol{1　(0&lt;a\\leqq 1)}\\\\ \\boldsymbol{a　(a&gt;1)}\\end{cases}$</p>",
    

    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin x-\\sin x^{2}}{x-x^{2}}$":
    // 平均値の定理を使った極限
    "<p>$f(x)=\\sin x$ とおく．</p><p>(ⅰ) $0&lt;x &lt; 1$ のとき，平均値の定理より</p><p style=\"text-align: center\">$\\displaystyle \\dfrac{f(x) -f(x^2)}{x-x^{2}}= f'(c_{1})=\\cos c_{1}$，$x^{2}&lt;c_{1} &lt; x$</p><p>を満たす $c_{1}$ が存在．$\\displaystyle \\lim_{x\\to +0}x^{2}=\\lim_{x\\to +0}x=0$ より，$\\displaystyle \\lim_{x\\to +0}c_{1}=0$ なので</p><p style=\"text-align: center\">$\\displaystyle \\lim_{x \\to +0}\\dfrac{\\sin x-\\sin x^{2}}{x-x^{2}}=\\lim_{x \\to +0}\\cos c_{1}=1$</p><p>(ⅱ) $x &lt; 0$ のとき，平均値の定理より</p><p style=\"text-align: center\">$\\displaystyle \\dfrac{f(x^2) -f(x)}{x^{2}-x}= f'(c_{2})=\\cos c_{2}$，$x&lt;c_{2} &lt; x^{2}$</p><p>を満たす $c_{2}$ が存在．$\\displaystyle \\lim_{x\\to -0}x=\\lim_{x\\to -0}x^{2}=0$ より，$\\displaystyle \\lim_{x\\to -0}c_{2}=0$ なので</p><p style=\"text-align: center\">$\\displaystyle \\lim_{x \\to -0}\\dfrac{\\sin x-\\sin x^{2}}{x-x^{2}}=\\lim_{x \\to -0}\\dfrac{\\sin x^{2}-\\sin x}{x^{2}-x}=\\lim_{x \\to -0}\\cos c_{2}=1$</p><p>以上より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin x-\\sin x^{2}}{x-x^{2}}=\\boldsymbol{1}$</p>",
    

    "$\\displaystyle \\lim_{x \\to \\infty}\\left(\\cos^{2}\\sqrt{x+1}+\\sin^{2}\\sqrt{x}\\right)$":
    // 平均値の定理を使った極限，2020一橋後期
    "<p>　$\\displaystyle \\lim_{x \\to \\infty}\\left(\\cos^{2}\\sqrt{x+1}+\\sin^{2}\\sqrt{x}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\left(\\dfrac{\\cos^{2}\\sqrt{x+1}-\\cos^{2}\\sqrt{x}}{x+1-x}+1\\right)$</p><p>$f(t)=\\cos^{2}\\sqrt{t}$ とおくと</p><p style=\"text-align: center\">$f'(t)=2\\cos\\sqrt{t}(-\\sin\\sqrt{t})\\dfrac{1}{2}t^{-\\frac{1}{2}}=-\\dfrac{\\sin2\\sqrt{t}}{2\\sqrt{t}}$</p><p>平均値の定理より</p><p style=\"text-align: center\">$\\dfrac{f(x+1)-f(x)}{x+1-x}=f'(c)$</p><p>を満たす実数 $c$ が $x&lt;c&lt;x+1$ に存在．これより $\\displaystyle \\lim_{x \\to \\infty}c=\\infty$．さらに</p><p style=\"text-align: center\">$-\\dfrac{1}{2\\sqrt{t}}\\leqq-\\dfrac{\\sin2\\sqrt{t}}{2\\sqrt{t}}\\leqq\\dfrac{1}{2\\sqrt{t}}$</p><p>から $\\displaystyle \\lim_{t \\to \\infty}\\left(-\\dfrac{1}{2\\sqrt{t}}\\right)=\\lim_{t \\to \\infty}\\dfrac{1}{2\\sqrt{t}}=0$ より $\\displaystyle \\lim_{t \\to \\infty}\\left(-\\dfrac{\\sin2\\sqrt{t}}{2\\sqrt{t}}\\right)=0$．よって</p><p>　$\\displaystyle \\lim_{x \\to \\infty}\\left(\\cos^{2}\\sqrt{x+1}+\\sin^{2}\\sqrt{x}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\left(\\dfrac{f(x+1)-f(x)}{x+1-x}+1\\right)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\left(f'(c)+1\\right)$</p><p>$\\displaystyle =\\lim_{c \\to \\infty}\\left(-\\dfrac{\\sin2\\sqrt{c}}{2\\sqrt{c}}+1\\right)$</p><p>$=\\boldsymbol{1}$</p>",
    

    "$\\displaystyle \\lim_{x \\to \\frac{\\pi}{2}}(\\sin x)^{\\tan^{2}x}$":
    // 2023京大実践
    "<p>　$\\displaystyle \\lim_{x \\to \\frac{\\pi}{2}}(\\sin x)^{\\tan^{2}x}$</p><p>$\\displaystyle =\\displaystyle \\lim_{t \\to 0}\\left\\{\\sin\\left(\\dfrac{\\pi}{2}-t\\right)\\right\\}^{\\tan^{2}\\left(\\frac{\\pi}{2}-t\\right)}$ $\\left(t=\\dfrac{\\pi}{2}-x\\right)$</p><p>$\\displaystyle =\\displaystyle \\lim_{t \\to 0}\\left(\\cos t\\right)^{\\frac{1}{\\tan^{2}t}}$</p><p>$\\displaystyle =\\displaystyle \\lim_{t \\to 0}\\left(\\cos^{2}t\\right)^{\\frac{1}{2\\tan^{2}t}}$</p><p>$\\displaystyle =\\displaystyle \\lim_{t \\to 0}\\left(\\dfrac{1}{1+\\tan^{2}t}\\right)^{\\frac{1}{2\\tan^{2}t}}$</p><p>$\\displaystyle =\\displaystyle \\lim_{t \\to 0}\\left\\{\\left(1+\\tan^{2}t\\right)^{\\frac{1}{\\tan^{2}t}}\\right\\}^{-\\frac{1}{2}}$</p><p>$=\\boldsymbol{e^{-\\frac{1}{2}}}$</p>",
    

    "$\\displaystyle \\lim_{x \\to \\infty}\\dfrac{\\log x}{x}$":
    // 微分による不等式の証明，サイトの練習改題，x/e^{x}の極限関連
    "<p>$f(x)=\\sqrt{x}-\\log x$ $(x&gt; 0)$ とおくと</p><p>$f'(x)=\\dfrac{1}{2\\sqrt{x}}-\\dfrac{1}{x}=\\dfrac{\\sqrt{x}-2}{2x}$</p><p>増減表は</p><table border=\"1px\" cellpadding=\"10px\" style=\"border-collapse: collapse;text-align: center\" align=\"center\"><caption></caption><tr><th>$x$</th><td>$0$</td><td>$\\cdots$</td><td>$4$</td><td>$\\cdots$</td></tr><tr><th>$f'(x)$</th><td>$0$</td><td>$-$</td><td>$0$</td><td>$+$</td></tr><tr><th>$f(x)$</th><td></td><td>↘︎</td><td>$2-2\\log2$</td><td>↗︎</td></tr></table><br><p>これより $f(x)\\geqq 2-2\\log2&gt;0$</p><p style=\"text-align: center\">$\\therefore \\ \\log x&lt;\\sqrt{x}$ $(x&gt;0)$</p><p>両辺を正の $x$ で割ると，$x&gt;1$ において</p><p style=\"text-align: center\">$0&lt;\\dfrac{\\log x}{x}&lt;\\dfrac{1}{\\sqrt{x}}$ $(x&gt;1)$</p><p>が成り立つ．$\\displaystyle \\lim_{x \\to \\infty}\\dfrac{1}{\\sqrt{x}}=0$ より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{x \\to \\infty}\\dfrac{\\log x}{x}=\\boldsymbol{0}$</p><p><b style=\"color: black\">別解</b></p><p>$t=\\log x$ とおくと $\\displaystyle \\lim_{x \\to \\infty}\\dfrac{\\log x}{x}=\\lim_{t \\to \\infty}\\dfrac{t}{e^{t}}=\\lim_{x \\to \\infty}\\dfrac{x}{e^{x}}$ となる．<p>$f(x)=e^{x}-1-x-\\dfrac{x^{2}}{2}$ $(x&gt;0)$ とおく．</p><p>$f'(x)=e^{x}-1-x$</p><p>$f''(x)=e^{x}-1&gt;0$ $(x&gt;0)$ </p><p>これより $f'(x)$ は単調増加．$f'(0)=0$ より $f'(x)&gt;0$．</p><p>これより $f(x)$ は単調増加．$f(0)=0$ より $f(x)&gt;0$．</p><p style=\"text-align: center\">$\\therefore \\ e^{x}&gt;1+x+\\dfrac{x^{2}}{2}$ $(x&gt;0)$</p><p>両辺 $x$ で割って逆数とると</p><p style=\"text-align: center\">$0&lt;\\dfrac{x}{e^{x}}&lt;\\dfrac{1}{\\dfrac{1}{x}+1+\\dfrac{x}{2}}$ $(x&gt;0)$</p><p>$\\displaystyle \\lim_{x \\to \\infty}\\dfrac{1}{\\dfrac{1}{x}+1+\\dfrac{x}{2}}=0$ より $\\displaystyle \\lim_{x \\to \\infty}\\dfrac{x}{e^{x}}=\\lim_{x \\to \\infty}\\dfrac{\\log x}{x}=\\boldsymbol{0}$</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\int_{0}^{\\pi}x^{2}|\\sin nx|\\,dx$":
    // 1989東工大
    "<p>　$\\displaystyle \\int_{0}^{\\pi}x^{2}|\\sin nx|\\,dx$</p><p>$\\displaystyle =\\int_{0}^{n\\pi}\\dfrac{t^{2}}{n^{2}}|\\sin t|\\dfrac{1}{n}\\,dt$　$(t=nx)$</p><p>$\\displaystyle =\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}\\int_{(k-1)\\pi}^{k\\pi}t^{2}|\\sin t|\\,dt$</p><p>$\\displaystyle =\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}\\int_{(k-1)\\pi}^{k\\pi}t^{2}(-1)^{k-1}\\sin t\\,dt$</p><p>$\\displaystyle =\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}(-1)^{k-1}\\int_{(k-1)\\pi}^{k\\pi}t^{2}\\sin t\\,dt$</p><p>$\\displaystyle =\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}(-1)^{k-1}\\Bigl[-t^{2}\\cos t+2t\\sin t+2\\cos t\\Bigr]_{(k-1)\\pi}^{k\\pi}$</p><p>$\\displaystyle =\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}(-1)^{k-1}\\left\\{-k^{2}\\pi^{2}(-1)^{k}+2(-1)^{k}+(k-1)^{2}\\pi^{2}(-1)^{k-1}-2(-1)^{k-1}\\right\\}$</p><p>$\\displaystyle =\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}(-1)^{k-1}\\left\\{k^{2}\\pi^{2}(-1)^{k-1}-2(-1)^{k-1}+(k-1)^{2}\\pi^{2}(-1)^{k-1}-2(-1)^{k-1}\\right\\}$</p><p>$\\displaystyle =\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}(-1)^{2k-2}\\left\\{(2k^{2}-2k+1)\\pi^{2}-4\\right\\}$</p><p>$\\displaystyle =\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}\\left\\{(2k^{2}-2k+1)\\pi^{2}-4\\right\\}$</p><p>以上より</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\int_{0}^{\\pi}x^{2}|\\sin nx|\\,dx$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n^{3}}\\sum_{k=1}^{n}\\left\\{(2k^{2}-2k+1)\\pi^{2}-4\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\left\\{\\dfrac{\\pi^{2}}{3}\\left(1+\\dfrac{1}{n}\\right)\\left(2+\\dfrac{1}{n}\\right)-\\dfrac{\\pi^{2}}{n}\\left(1+\\dfrac{1}{n}\\right)+\\dfrac{\\pi^{2}-4}{n^2}\\right\\}$</p><p>$=\\boldsymbol{\\dfrac{2}{3}\\pi^{2}}$</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{\\sin^{2}nx}{1+x}\\,dx$":
    // 1999東工大，プラチカ
    "<p>　$\\displaystyle \\int_{0}^{\\frac{\\pi}{2}}\\dfrac{\\sin^{2}nx}{1+x}\\,dx$</p><p>$\\displaystyle =\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{1-\\cos 2nx}{2(1+x)}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{2}\\Bigl[\\log(1+x)\\Bigr]_{0}^{\\frac{\\pi}{2}}-\\dfrac{1}{2}\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{\\cos 2nx}{1+x}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{2}\\log\\left(1+\\dfrac{\\pi}{2}\\right)-\\dfrac{1}{2}\\left\\{\\left[\\dfrac{\\sin 2nx}{2n(1+x)}\\right]_{0}^{\\frac{\\pi}{2}}-\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{-\\sin 2nx}{2n(1+x)^{2}}\\,dx\\right\\}$</p><p>$\\displaystyle =\\dfrac{1}{2}\\log\\left(1+\\dfrac{\\pi}{2}\\right)-\\dfrac{1}{4n}\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{\\sin 2nx}{(1+x)^{2}}\\,dx$</p><p>$0\\leqq x\\leqq \\dfrac{\\pi}{2}$ において $-1&lt; \\dfrac{\\sin 2nx}{(1+x)^{2}}&lt; 1$ より</p><p style=\"text-align: center\">$\\displaystyle -\\dfrac{1}{4n}\\int_{0}^{\\frac{\\pi}{2}}\\,dx&lt; \\dfrac{1}{4n}\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{\\sin 2nx}{(1+x)^{2}}\\,dx&lt; \\dfrac{1}{4n}\\int_{0}^{\\frac{\\pi}{2}}\\,dx$</p><p style=\"text-align: center\">$\\displaystyle \\therefore \\ -\\dfrac{\\pi}{8n}&lt; \\dfrac{1}{4n}\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{\\sin 2nx}{(1+x)^{2}}\\,dx&lt; \\dfrac{\\pi}{8n}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\left(-\\dfrac{\\pi}{8n}\\right)=\\lim_{n \\to \\infty}\\dfrac{\\pi}{8n}=0$ より $\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{4n}\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{\\sin 2nx}{(1+x)^{2}}\\,dx=0$．</p><p style=\"text-align: center\"></p><p style=\"text-align: center\">$\\therefore \\ \\displaystyle \\lim_{n \\to \\infty}\\int_{0}^{\\frac{\\pi}{2}}\\dfrac{\\sin^{2}nx}{1+x}\\,dx=\\boldsymbol{\\dfrac{1}{2}\\log\\left(1+\\dfrac{\\pi}{2}\\right)}$</p>",
    

    "$\\displaystyle \\lim_{x \\to \\sqrt{\\pi}}\\int_{\\sqrt{\\pi}}^{x}\\dfrac{(x^{2}+\\sqrt{\\pi}t)e^{t^2}}{(x^{3}-\\sqrt{\\pi}x^{2}+\\pi x-\\pi\\sqrt{\\pi})t^{2}\\log t}\\,dt$":
    // 2017日本医科大
    "<p>　$\\displaystyle \\int_{\\sqrt{\\pi}}^{x}\\dfrac{(x^{2}+\\sqrt{\\pi}t)e^{t^2}}{(x^{3}-\\sqrt{\\pi}x^{2}+\\pi x-\\pi\\sqrt{\\pi})t^{2}\\log t}\\,dt$</p><p>$\\displaystyle =\\dfrac{1}{(x^{2}+\\pi)(x-\\sqrt{\\pi})}\\int_{\\sqrt{\\pi}}^{x}\\dfrac{(x^{2}+\\sqrt{\\pi}t)e^{t^2}}{t^{2}\\log t}\\,dt$</p><p>$\\displaystyle =\\dfrac{x^{2}}{x^{2}+\\pi}\\cdot \\dfrac{1}{x-\\sqrt{\\pi}}\\int_{\\sqrt{\\pi}}^{x}f(t)\\,dt+\\dfrac{\\sqrt{\\pi}}{x^{2}+\\pi}\\cdot \\dfrac{1}{x-\\sqrt{\\pi}}\\int_{\\sqrt{\\pi}}^{x}g(t)\\,dt$　$\\left(f(t)=\\dfrac{e^{t^2}}{t^{2}\\log t}，g(t)=\\dfrac{e^{t^2}}{t\\log t}\\right)$</p><p>　$\\displaystyle \\lim_{x \\to \\sqrt{\\pi}}\\int_{\\sqrt{\\pi}}^{x}\\dfrac{(x^{2}+\\sqrt{\\pi}t)e^{t^2}}{(x^{3}-\\sqrt{\\pi}x^{2}+\\pi x-\\pi\\sqrt{\\pi})t^{2}\\log t}\\,dt$</p><p>$\\displaystyle =\\dfrac{\\pi}{\\pi+\\pi}f(\\sqrt{\\pi})+\\dfrac{\\sqrt{\\pi}}{\\pi+\\pi}g(\\sqrt{\\pi})$</p><p>$\\displaystyle =\\dfrac{1}{2}\\cdot\\dfrac{e^{\\pi}}{\\pi\\log \\sqrt{\\pi}}+\\dfrac{\\sqrt{\\pi}}{2\\pi}\\cdot\\dfrac{e^{\\pi}}{\\sqrt{\\pi}\\log \\sqrt{\\pi}}$</p><p>$\\displaystyle =\\boldsymbol{\\dfrac{2e^{\\pi}}{\\pi\\log \\pi}}$</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\int_{0}^{\\frac{\\pi}{4}}\\tan^{n}x\\,dx$":
    // 
    "<p>$\\displaystyle I_{n}=\\int_{0}^{\\frac{\\pi}{4}} \\tan^{n}x\\,dx$ とおく</p><p>　$I_{n+2}$</p><p>$\\displaystyle =\\int_{0}^{\\frac{\\pi}{4}} \\tan^{n+2}x\\,dx$</p><p>$\\displaystyle =\\int_{0}^{\\frac{\\pi}{4}} \\tan^{n}x\\left(\\dfrac{1}{\\cos^{2}x}-1\\right)\\,dx$</p><p>$\\displaystyle =\\int_{0}^{1} u^{n}\\,du-\\int_{0}^{\\frac{\\pi}{4}} \\tan^{n}x\\,dx$　( $u=\\tan x$ )</p><p>$\\displaystyle =\\dfrac{1}{n+1}-I_{n}$</p><p>$\\Longleftrightarrow \\ I_{n}+I_{n+2}=\\dfrac{1}{n+1}$</p><p>$0 \\leqq x \\leqq \\dfrac{\\pi}{4}$ において，$0 \\leqq \\tan x \\leqq 1$ より，$I_{n}\\geqq 0$．これより $I_{n+2}\\geqq 0$ でもあるので</p><p style=\"text-align: center\">$0\\leqq I_{n}\\leqq I_{n}+I_{n+2}=\\dfrac{1}{n+1}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n+1}=0$ より，$\\displaystyle \\lim_{n \\to \\infty}I_{n}=\\boldsymbol{0}$</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{2n}(-1)^{k}\\left(\\dfrac{k}{2n}\\right)^{100}$":
    // 
    "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{2n}(-1)^{k}\\left(\\dfrac{k}{2n}\\right)^{100}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\left\\{\\sum_{m=1}^{n}(-1)^{2m}\\left(\\dfrac{2m}{2n}\\right)^{100}+\\sum_{m=1}^{n}(-1)^{2m-1}\\left(\\dfrac{2m-1}{2n}\\right)^{100}\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{m=1}^{n}\\left\\{\\left(\\dfrac{2m}{2n}\\right)^{100}-\\left(\\dfrac{2m-1}{2n}\\right)^{100}\\right\\}$</p><p>$f(x)=x^{100}$ とおくと，平均値の定理より</p><p style=\"text-align: center\">$\\dfrac{f\\left(\\dfrac{2m}{2n}\\right)-f\\left(\\dfrac{2m-1}{2n}\\right)}{\\dfrac{2m}{2n}-\\dfrac{2m-1}{2n}}=f'(c)$</p><p>つまり</p><p style=\"text-align: center\">$\\left(\\dfrac{2m}{2n}\\right)^{100}-\\left(\\dfrac{2m-1}{2n}\\right)^{100}=\\dfrac{1}{2n}\\cdot100c^{99}$</p><p>を満たす $c$ が $\\dfrac{2m-1}{2n}&lt;c&lt;\\dfrac{2m}{2n}$ に存在．</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{2n}(-1)^{k}\\left(\\dfrac{k}{2n}\\right)^{100}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{m=1}^{n}\\dfrac{1}{2n}\\cdot100c^{99}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{50}{n}\\sum_{m=1}^{n}c^{99}$</p><p>ここで</p><p style=\"text-align: center\">$\\displaystyle \\dfrac{50}{n}\\sum_{m=1}^{n}\\left(\\dfrac{2m-1}{2n}\\right)^{99}&lt;\\dfrac{50}{n}\\sum_{m=1}^{n}c^{99}&lt;\\dfrac{50}{n}\\sum_{m=1}^{n}\\left(\\dfrac{2m}{2n}\\right)^{99}$</p><p>より</p><div style=\"text-align: center\"><img src=\"noteimages/limit-gacha1.png\" width=\"75%\"></div><p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{50}{n}\\sum_{m=1}^{n}\\left(\\dfrac{2m-1}{2n}\\right)^{99}$</p><p>$\\displaystyle =50\\int_{0}^{1}x^{99}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{2}$</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{50}{n}\\sum_{m=1}^{n}\\left(\\dfrac{2m}{2n}\\right)^{99}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{50}{n}\\sum_{m=1}^{n}\\left(\\dfrac{m}{n}\\right)^{99}$</p><p>$\\displaystyle =50\\int_{0}^{1}x^{99}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{2}$</p><p>以上から</p><p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{2n}(-1)^{k}\\left(\\dfrac{k}{2n}\\right)^{100}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{50}{n}\\sum_{m=1}^{n}c^{99}$</p><p>$=\\boldsymbol{\\dfrac{1}{2}}$</p>",
    

    "$\\displaystyle \\lim_{x\\to \\infty}\\int_{0}^{x}|\\sin t|e^{-t}\\,dt$":
    // 
    "<p>$n\\pi \\leqq x \\leqq (n+1)\\pi$ において，$|\\sin t|e^{-t}&gt;0$ より</p><p style=\"text-align: center\">$\\displaystyle \\int_{0}^{n\\pi}|\\sin t|e^{-t}\\,dt\\leqq \\int_{0}^{x}|\\sin t|e^{-t}\\,dt\\leqq \\int_{0}^{(n+1)\\pi}|\\sin t|e^{-t}\\,dt$</p><p>から，最左辺を求める．</p><p>まず，$\\displaystyle I=\\int_{}^{} \\ e^{-t}\\sin t\\,dx$ とおくと</p><p>　$\\displaystyle I$</p><p>$\\displaystyle =-e^{-t}\\sin t+\\int_{}^{} \\ e^{-t}\\cos t\\,dt$</p><p>$\\displaystyle =-e^{-t}\\sin t-e^{-t}\\cos t-I$</p><p>$\\displaystyle \\therefore \\ I=-\\dfrac{e^{-t}}{2}(\\sin t+\\cos t)+C$ ( $C$ は積分定数)</p><p>　$\\displaystyle \\int_{0}^{n\\pi}|\\sin t|e^{-t}\\,dt$</p><p>$\\displaystyle =\\sum_{k=0}^{n-1}\\int_{k\\pi}^{(k+1)\\pi}|\\sin t|e^{-t}\\,dt$</p><p>$\\displaystyle =\\sum_{k=0}^{n-1}\\int_{0}^{\\pi}|\\sin (u+k\\pi)|e^{-u-k\\pi}\\,du$　$(u=t-k\\pi)$</p><p>$\\displaystyle =\\sum_{k=0}^{n-1}e^{-k\\pi}\\int_{0}^{\\pi}|\\sin u \\cos k\\pi+\\cos u \\sin k\\pi|e^{-u}\\,du$</p><p>$\\displaystyle =\\sum_{k=0}^{n-1}e^{-k\\pi}\\int_{0}^{\\pi}|\\sin u||\\cos k\\pi|e^{-u}\\,du$</p><p>$\\displaystyle =\\sum_{k=0}^{n-1}e^{-k\\pi}\\int_{0}^{\\pi}e^{-u}\\sin u\\,du$</p><p>$\\displaystyle =\\sum_{k=0}^{n-1}e^{-k\\pi}\\left[-\\dfrac{e^{-t}}{2}(\\sin t+\\cos t)\\right]_{0}^{\\pi}$</p><p>$\\displaystyle =\\dfrac{e^{-\\pi}+1}{2}\\sum_{k=0}^{n-1}e^{-k\\pi}$</p><p>以上より，$n\\pi \\leqq x \\leqq (n+1)\\pi$ において</p><p style=\"text-align: center\">$\\displaystyle \\dfrac{e^{-\\pi}+1}{2}\\sum_{k=0}^{n-1}e^{-k\\pi}\\leqq \\int_{0}^{x}|\\sin t|e^{-t}\\,dt\\leqq \\dfrac{e^{-\\pi}+1}{2}\\sum_{k=0}^{n}e^{-k\\pi}$</p><p>ここで $n \\to \\infty$ のとき，$x \\to \\infty$ であり</p><p>$\\displaystyle \\lim_{n\\to \\infty}\\dfrac{e^{-\\pi}+1}{2}\\sum_{k=0}^{n-1}e^{-k\\pi}=\\lim_{n\\to \\infty}\\dfrac{e^{-\\pi}+1}{2}\\sum_{k=0}^{n}e^{-k\\pi}=\\dfrac{e^{-\\pi}+1}{2}\\cdot \\dfrac{1}{1-e^{-\\pi}}$</p><p>より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{x\\to \\infty}\\int_{0}^{x}|\\sin t|e^{-t}\\,dt=\\boldsymbol{\\dfrac{e^{\\pi}+1}{2(e^{\\pi}-1)}}$</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\int_{1}^{e}x^{m}(\\log x)^{n}\\,dx$　$( \\ m，n \\ は自然数 \\ )$":
    // 
    "<p>$\\displaystyle I(m,n)=\\int_{1}^{e}x^{m}(\\log x)^{n}\\,dx$ とおく．</p><p>　$I(m,n)$</p><p>$\\displaystyle =\\int_{1}^{e}x^{m}(\\log x)^{n}\\,dx$</p><p>$\\displaystyle =\\left[\\dfrac{1}{m+1}x^{m+1}(\\log x)^{n}\\right]_{1}^{e}-\\int_{1}^{e}\\dfrac{1}{m+1}x^{m+1}\\cdot n(\\log x)^{n-1}\\cdot\\dfrac{1}{x}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{m+1}e^{m+1}-\\dfrac{n}{m+1}I(m,n-1)$</p><p>$\\Longleftrightarrow \\ \\dfrac{n}{m+1}I(m,n-1)=\\dfrac{1}{m+1}e^{m+1}-I(m,n)$</p><p style=\"text-align: center\">$\\therefore \\ \\dfrac{n+1}{m+1}I(m,n)=\\dfrac{1}{m+1}e^{m+1}-I(m,n+1)$</p><p>ここで，$1\\leqq x \\leqq e$ において $x^{m}(\\log x)^{n}\\geqq0$ より $I(m,n)\\geqq 0$ なので</p><p style=\"text-align: center;\">$\\dfrac{n+1}{m+1}I(m,n)\\leqq \\dfrac{1}{m+1}e^{m+1}$</p><p style=\"text-align: center;\">$\\therefore \\ 0\\leqq I(m,n)\\leqq \\dfrac{e^{m+1}}{n+1}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{e^{m+1}}{n+1}=0$ より</p><p style=\"text-align: center;\">$\\displaystyle \\lim_{n \\to \\infty}I(m,n)=\\boldsymbol{0}$</p>",
    
},
        "D": {
           
    "$\\displaystyle \\lim_{x \\to 0}\\left(\\dfrac{\\sin x}{x}\\right)^{\\frac{1}{x^{2}}}$":
    // 超級1，ごよ
    "<p>TBA</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{3-\\sqrt[n]{3}}{2}\\right)^{n}$":
    // 超級2，ごよ
    "<p>TBA</p>",
    

    "$\\displaystyle \\lim_{x \\to \\infty}x\\left\\{e-\\left(1+\\dfrac{1}{x}\\right)^{x}\\right\\}$":
    // 超級3，ごよ
    "<p>TBA</p>",
    

    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\dfrac{1}{n^{\\frac{3}{2}}}\\left[\\sqrt{2k-1}\\right]$":
    // 超級4，AKR，格子点，奇数和の区分求積
    "<p>TBA</p>",  
}
    },
    "2": {
        "A": {
            "$\\displaystyle \\frac{d}{dx}(e^x)$": "<p>$\\displaystyle \\frac{d}{dx}(e^x) = e^x$</p>"
        },
        "B": {
            "$\\displaystyle \\frac{d}{dx}(x^3)$": "<p>$\\displaystyle \\frac{d}{dx}(x^3) = 3x^2$</p>"
        },
        "C": {
            "$\\displaystyle \\int_0^1 x^3 \\, dx$": "<p>$\\displaystyle \\int_0^1 x^3 \\, dx = \\frac{1}{4}$</p>"
        },
        "D": {
            "$\\displaystyle \\int_{0}^{\\infty} e^{-x} \\, dx$": "<p>$\\displaystyle \\int_{0}^{\\infty} e^{-x} \\, dx = 1$</p>"
        }
    },
    "1": {
        "A": {
            "$\\displaystyle \\frac{d}{dx}(e^x)$": "<p>$\\displaystyle \\frac{d}{dx}(e^x) = e^x$</p>"
        },
        "B": {
            "$\\displaystyle \\frac{d}{dx}(x^3)$": "<p>$\\displaystyle \\frac{d}{dx}(x^3) = 3x^2$</p>"
        },
        "C": {
            "$\\displaystyle \\int_0^1 x^3 \\, dx$": "<p>$\\displaystyle \\int_0^1 x^3 \\, dx = \\frac{1}{4}$</p>"
        },
        "D": {
            "$\\displaystyle \\int_{0}^{\\infty} e^{-x} \\, dx$": "<p>$\\displaystyle \\int_{0}^{\\infty} e^{-x} \\, dx = 1$</p>"
        }
    },
    "4": {
        "A": {
            "$\\displaystyle \\int_0^\\infty \\frac{\\sin(x)}{x} \\, dx$": "<p>$\\displaystyle \\int_0^\\infty \\frac{\\sin(x)}{x} \\, dx = \\frac{\\pi}{2}$</p>"
        },
        "B": {
            "$\\displaystyle \\zeta(2)$": "<p>$\\displaystyle \\zeta(2) = \\frac{\\pi^2}{6}$</p>"
        },
        "C": {
            "$\\displaystyle \\int_{-\\infty}^{\\infty} e^{-x^2} dx$": "<p>$\\displaystyle \\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}$</p>"
        },
        "D": {
            "$\\displaystyle \\frac{d}{dx}(\\ln(x))$": "<p>$\\displaystyle \\frac{d}{dx}(\\ln(x)) = \\frac{1}{x}$</p>"
        }
    }
}

console.log(gachaItems);