const items = {
    "1": { // Level 1
        "a": [
              "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{2n+11}{n^{2}+2n+4}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{2n+11}{n^{2}+2n+4}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{2+\\dfrac{11}{n}}{n+2+\\dfrac{4}{n}}$</p><p>$=\\boldsymbol{0}$</p>",
    // 普通，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+3)(4n+1)}{n^{2}-5n+1}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+3)(4n+1)}{n^{2}-5n+1}$</p><p>$=\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\left(1+\\dfrac{3}{n}\\right)\\left(4+\\dfrac{1}{n}\\right)}{1-\\dfrac{5}{n}+\\dfrac{1}{n^{2}}}$</p><p>$=\\boldsymbol{4}$</p>",
    // 普通，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{_{2n+2}{\\rm C}_{n+1}}{_{2n}{\\rm C}_{n}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{_{2n+2}{\\rm C}_{n+1}}{_{2n}{\\rm C}_{n}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{(2n+2)!}{(n+1)!(n+1!)}\\cdot \\dfrac{n!n!}{2n!}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{(2n+2)(2n+1)}{(n+1)^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{2\\left(2+\\dfrac{1}{n}\\right)}{1+\\dfrac{1}{n}}$</p>",
    // 普通，2023関西大
    "$\\displaystyle \\lim_{n \\to \\infty}(\\sqrt{n^{2}+5n-3}-\\sqrt{n^{2}+1})$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}(\\sqrt{n^{2}+5n-3}-\\sqrt{n^{2}+1})$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}(\\sqrt{n^{2}+5n-3}-\\sqrt{n^{2}+1})\\cdot\\dfrac{\\sqrt{n^{2}+5n-3}+\\sqrt{n^{2}+1}}{\\sqrt{n^{2}+5n-3}+\\sqrt{n^{2}+1}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{(n^{2}+5n-3)-(n^{2}+1)}{\\sqrt{n^{2}+5n-3}+\\sqrt{n^{2}+1}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{5n-4}{\\sqrt{n^{2}+5n-3}+\\sqrt{n^{2}+1}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{5-\\dfrac{4}{n}}{\\sqrt{1+\\dfrac{5}{n}-\\dfrac{3}{n^2}}+\\sqrt{1+\\dfrac{1}{n^2}}}$</p><p>$=\\dfrac{5}{1+1}=\\boldsymbol{\\dfrac{5}{2}}$</p>",
    // 普通，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1+2+\\cdots+n}{n^2}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1+2+\\cdots+n}{n^2}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\dfrac{1}{2}n(n+1)}{n^2}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{2}\\left(1+\\dfrac{1}{n}\\right)$</p><p>$=\\boldsymbol{\\dfrac{1}{2}}$</p>",
    //普通の極限，ごよ１
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{3n^{2}+n+1}{n+1}-3n\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{3n^{2}+n+1}{n+1}-3n\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{-2n+1}{n+1}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{-2+\\dfrac{1}{n}}{1+\\dfrac{1}{n}}$</p><p>$=\\boldsymbol{-2}$</p>",
    //普通，ごよ２
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{\\sqrt{n^{2}+n}-n}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{\\sqrt{n^{2}+n}-n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{\\sqrt{n^{2}+n}-n}\\cdot \\dfrac{\\sqrt{n^{2}+n}+n}{\\sqrt{n^{2}+n}+n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\sqrt{n^{2}+n}+n}{n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sqrt{1+\\dfrac{1}{n}}+1$</p><p>$=\\boldsymbol{2}$</p>",
    //有理化，ごよ３
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sqrt{n+1}-\\sqrt{n-3}}{\\sqrt{n+2}-\\sqrt{n-2}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sqrt{n+1}-\\sqrt{n-3}}{\\sqrt{n+2}-\\sqrt{n-2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\sqrt{n+1}-\\sqrt{n-3}}{\\sqrt{n+2}-\\sqrt{n-2}}\\cdot\\dfrac{\\sqrt{n+2}+\\sqrt{n-2}}{\\sqrt{n+2}+\\sqrt{n-2}}\\cdot\\dfrac{\\sqrt{n+1}+\\sqrt{n-3}}{\\sqrt{n+1}+\\sqrt{n-3}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{4}{4}\\cdot\\dfrac{\\sqrt{n+2}+\\sqrt{n-2}}{\\sqrt{n+1}+\\sqrt{n-3}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\sqrt{1+\\dfrac{2}{n}}+\\sqrt{1-\\dfrac{2}{n}}}{\\sqrt{1+\\dfrac{1}{n}}+\\sqrt{1-\\dfrac{3}{n}}}$</p><p>$=\\boldsymbol{1}$</p>",
    //有理化，Z会M3JA2
    "$\\displaystyle \\lim_{n \\to \\infty} \\log_3 \\dfrac{\\sqrt[n]{7}}{5^n}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\log_3 \\dfrac{\\sqrt[n]{7}}{5^n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\left(\\log_3 \\sqrt[n]{7} -\\log_3{5^n}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\left(\\dfrac{1}{n}\\log_3 7 -n\\log_3 5\\right)$</p><p>$=\\boldsymbol{-\\infty}$</p>",
    //対数，ごよ４
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+1)+(n+2)+\\cdots+2n}{1+2+\\cdots+n}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{(n+1)+(n+2)+\\cdots+2n}{1+2+\\cdots+n}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{(n+1+2n)n\\cdot \\dfrac{1}{2}}{\\sum\\limits_{k=1}^{n}k}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{3n+1}{n+1}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{3+\\dfrac{1}{n}}{1+\\dfrac{1}{n}}$</p><p>$=\\boldsymbol{3}$</p>",
    //和，ごよ５，アプリ版専用
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sin n}{n}$": "<p>$-1\\leqq \\sin n \\leqq 1$ より</p><p style=\"text-align: center\">$-\\dfrac{1}{n}\\leqq \\dfrac{\\sin n}{n} \\leqq \\dfrac{1}{n}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\left(-\\dfrac{1}{n}\\right)=\\lim_{n \\to \\infty}\\dfrac{1}{n}=0$ より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{\\sin n}{n}=\\boldsymbol{0}$</p>",
    // はさみうち，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n^{2}+1}+\\dfrac{1}{n^{2}+2}+\\cdots+\\dfrac{1}{n^{2}+n}\\right)$ ": "<p>$\\displaystyle A_n=\\dfrac{1}{n^{2}+1}+\\dfrac{1}{n^{2}+2}+\\cdots+\\dfrac{1}{n^{2}+n}$ とおく．</p><p>$\\displaystyle 0 &lt; \\dfrac{1}{n^{2}+k} &lt; \\dfrac{1}{n^2}$ $(k=1,2,\\cdots,n)$ だから</p><p>$\\displaystyle 0 &lt; A_n &lt; \\dfrac{1}{n^2}+\\dfrac{1}{n^2}+\\cdots+\\dfrac{1}{n^2}=\\dfrac{1}{n^2}\\cdot n=\\dfrac{1}{n}$</p><p>$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n}=0$ より $\\displaystyle \\lim_{n \\to \\infty}A_n=\\boldsymbol{0}$</p>",
    //はさみうち，ごよ６
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{2(-3)^{n}+7\\cdot5^{n+1}}{5\\cdot3^{n+1}-2\\cdot 5^{n}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{2(-3)^{n}+7\\cdot5^{n+1}}{5\\cdot3^{n+1}-2\\cdot 5^{n}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{2\\left(-\\dfrac{3}{5}\\right)^{n}+35}{15\\left(\\dfrac{3}{5}\\right)^{n}-2}$</p><p>$=\\boldsymbol{-\\dfrac{35}{2}}$</p>",
    // 無限等比数列，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\{5^{n}-(-4)^n\\}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\{5^{n}-(-4)^n\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}5^{n} \\left\\{1- \\left( -\\dfrac{4}{5} \\right)^n \\right\\}$</p><p>$=\\boldsymbol{\\infty}$</p>",
    //等比，ごよ７
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{x^{n}+x+1}{x^{2n}+1}$　$( \\ x \\ は実数 \\ )$": "<p>$\\displaystyle f(x)=\\dfrac{x^{n}+x+1}{x^{2n}+1}$ とおく</p>(ⅰ) $|x|&lt;1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)$</p><p>$\\displaystyle =\\dfrac{0+x+1}{0+1}=x+1$</p><br><p>(ⅱ) $|x|&gt;1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{\\dfrac{1}{x^{n}}+\\dfrac{x+1}{x^{2n}}}{1+\\dfrac{1}{x^{2n}}}=0$</p><br><p>(ⅲ) $x=1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\dfrac{3}{2}$</p><br><p>(ⅳ) $x=-1$ のとき</p><p>分子の $x^{n}$ が振動するので定義されない．</p><p>以上より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\begin{cases} \\boldsymbol{x+1 \\ \\ \\ (-1&lt; x &lt; 1)} \\\\ \\boldsymbol{0 \\ \\ \\ (x&lt;-1，1&lt;x)} \\\\ \\boldsymbol{\\dfrac{3}{2} \\ \\ \\ (x=1)}\\end{cases}$</p>",
    // 無限等比数列，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{x^{2n+1}-1}{x^{2n}+1}$　$( \\ x \\ は実数 \\ )$": "<p>$\\displaystyle f(x)=\\dfrac{x^{2n+1}-1}{x^{2n}+1}$ とおく．</p><p>(i) $ |x| < 1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\dfrac{0-1}{0+1}=-1$</p><p>(ii) $ |x| > 1$ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\lim_{n \\to \\infty}\\dfrac{x-\\dfrac{1}{x^{2n}}}{1+\\dfrac{1}{x^{2n}}}=x$</p><p>(iii) $ x=1 $ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\dfrac{1-1}{1+1}=0$</p><p>(iv) $ x=-1 $ のとき</p><p>　$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\dfrac{-1-1}{1+1}=-1$</p><p>以上より</p><p style=\"text-align: center\">$\\displaystyle \\lim_{n \\to \\infty}f(x)=\\begin{cases} \\boldsymbol{-1 \\ \\ \\ (-1 \\leqq x < 1)} \\\\ \\boldsymbol{x \\ \\ \\ (x &lt; -1，1&lt;x)} \\\\ \\boldsymbol{0 \\ \\ \\ (x=1)}\\end{cases}$</p>",
    //等比場合分け，ごよ８
    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\dfrac{1}{(2k+1)(2k+3)}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\dfrac{1}{(2k+1)(2k+3)}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\dfrac{1}{2}\\left(\\dfrac{1}{2k+1}-\\dfrac{1}{2k+3}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{2}\\sum_{k=1}^{n}\\left(\\dfrac{1}{2k+1}-\\dfrac{1}{2k+3}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{2}\\left\\{\\left(\\dfrac{1}{3}-\\dfrac{1}{5}\\right)+\\left(\\dfrac{1}{5}-\\dfrac{1}{7}\\right)+\\cdots+\\left(\\dfrac{1}{2n+1}-\\dfrac{1}{2n+3}\\right)\\right\\}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{2}\\left(\\dfrac{1}{3}-\\dfrac{1}{2n+3}\\right)$</p><p>$=\\boldsymbol{\\dfrac{1}{6}}$</p>",
    // 無限級数，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\left(\\dfrac{1}{3^{k-1}}-\\dfrac{1}{4^{k}}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\left(\\dfrac{1}{3^{k-1}}-\\dfrac{1}{4^{k}}\\right)$</p><p>$=\\dfrac{1}{1-\\dfrac{1}{3}}-\\dfrac{\\dfrac{1}{4}}{1-\\dfrac{1}{4}}$</p><p>$\\displaystyle =\\dfrac{3}{2}-\\dfrac{1}{3}=\\boldsymbol{\\dfrac{7}{6}}$</p>",
    // 無限級数，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\left\\{2\\left(-\\dfrac{2}{3}\\right)^{k-1}+3\\left(\\dfrac{1}{4}\\right)^{k-1}\\right\\}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\left\\{2\\left(-\\dfrac{2}{3}\\right)^{k-1}+3\\left(\\dfrac{1}{4}\\right)^{k-1}\\right\\}$</p><p>$\\displaystyle =\\dfrac{2}{1- \\left(-\\dfrac{2}{3}\\right) }+\\dfrac{3}{1-\\dfrac{1}{4}}$</p><p>$\\displaystyle =\\dfrac{6}{5}+4$</p><p>$\\displaystyle =\\boldsymbol{\\dfrac{26}{5}}$</p>",
    //等比級数，ごよ９
    "$\\displaystyle \\lim_{x \\to 2}\\dfrac{x^{2}-5x+6}{x-2}$": "<p>　$\\displaystyle \\lim_{x \\to 2}\\dfrac{(x-2)(x-3)}{x-2}$</p><p>$\\displaystyle =\\lim_{x \\to 2}(x-3)$</p><p>$=\\boldsymbol{-1}$</p>",
    // 関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to 3}\\dfrac{\\sqrt{x+13}-4}{x-3}$": "<p>　$\\displaystyle \\lim_{x \\to 3}\\dfrac{\\sqrt{x+13}-4}{x-3}\\cdot\\dfrac{\\sqrt{x+13}+4}{\\sqrt{x+13}+4}$</p><p>$\\displaystyle =\\lim_{x \\to 3}\\dfrac{x-3}{(x-3)(\\sqrt{x+13}+4)}$</p><p>$\\displaystyle =\\lim_{x \\to 3}\\dfrac{1}{\\sqrt{x+13}+4}$</p><p>$\\displaystyle =\\boldsymbol{\\dfrac{1}{8}}$</p>",
    // 関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to -\\infty}(\\sqrt{x^{2}+5x}+x)$": "<p>　$\\displaystyle \\lim_{x \\to -\\infty}(\\sqrt{x^{2}+5x}+x)$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}(\\sqrt{x^{2}+5x}+x)\\cdot \\dfrac{\\sqrt{x^{2}+5x}-x}{\\sqrt{x^{2}+5x}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5x}{\\sqrt{x^{2}+5x}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5x}{\\sqrt{x^{2}}\\sqrt{1+\\dfrac{5}{x}}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5x}{|x|\\sqrt{1+\\dfrac{5}{x}}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5x}{-x\\sqrt{1+\\dfrac{5}{x}}-x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty}\\dfrac{5}{-\\sqrt{1+\\dfrac{5}{x}}-1}$</p><p>$\\displaystyle =\\boldsymbol{-\\dfrac{5}{2}}$</p><p><b style=\"color: black\">別解</b></p><p>　$\\displaystyle \\lim_{x \\to -\\infty}(\\sqrt{x^{2}+5x}+x)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}(\\sqrt{t^{2}-5t}-t)$　$(t=-x)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}(\\sqrt{t^{2}-5t}-t)\\cdot \\dfrac{\\sqrt{t^{2}-5t}+t}{\\sqrt{t^{2}-5t}+t}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\dfrac{-5t}{\\sqrt{t^{2}-5t}+t}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty}\\dfrac{-5}{\\sqrt{1-\\dfrac{5}{t}}+1}$</p><p>$\\displaystyle =\\boldsymbol{-\\dfrac{5}{2}}$</p>",
    // -∞有理化，サイトの例題
    "$\\displaystyle \\lim_{x \\to -\\infty} \\dfrac{4^x}{3^{x}+2^{x}}$": "<p>　$\\displaystyle \\lim_{x \\to -\\infty} \\dfrac{4^x}{3^x+2^x}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty} \\dfrac{2^x}{\\left(\\dfrac{3}{2}\\right)^{x}+1}$</p><p>$\\displaystyle =\\dfrac{0}{0+1}$</p><p>$=\\boldsymbol{0}$</p>",
    //-∞，ごよ１４
    "$\\displaystyle \\lim_{x \\to -\\infty} \\left(3x+1+\\sqrt{9x^2+1}\\right)$": "<p>　$\\displaystyle \\lim_{x \\to -\\infty} \\left(3x+1+\\sqrt{9x^2+1}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty} \\dfrac{(3x+1)^2-(9x^2+1)}{3x+1-\\sqrt{9x^2+1}}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty} \\dfrac{6x}{3x+1+x\\sqrt{9+\\dfrac{1}{x^2}}}$</p><p>$\\displaystyle =\\lim_{x \\to -\\infty} \\dfrac{6}{3+\\dfrac{1}{x}+\\sqrt{9+\\dfrac{1}{x^2}}}$</p><p>$\\displaystyle =\\dfrac{6}{3+\\sqrt{9}}$</p><p>$\\displaystyle =\\boldsymbol{1}$</p><p><b style=\"color: black\">別解</b></p><p>　$\\displaystyle \\lim_{x \\to -\\infty} \\left(3x+1+\\sqrt{9x^2+1}\\right)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty} \\left(-3t+1+\\sqrt{9t^2+1}\\right)　(t=-x)$</p><p>$\\displaystyle =\\lim_{t \\to \\infty} \\dfrac{(-3t+1)^2-(9t^2+1)}{-3t+1-\\sqrt{9t^2+1}}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty} \\dfrac{-6t}{-3t+1-\\sqrt{9t^2+1}}$</p><p>$\\displaystyle =\\lim_{t \\to \\infty} \\dfrac{-6}{-3+\\dfrac{1}{t}-\\sqrt{9+\\dfrac{1}{t^2}}}$</p><p>$\\displaystyle =\\dfrac{-6}{-3-\\sqrt{9}}$</p><p>$\\displaystyle =\\boldsymbol{1}$</p>",
    //-∞有理化，ごよ１５
    "$\\displaystyle \\lim_{x \\to -5+0}\\dfrac{x}{x+5}$": "<p>　$\\displaystyle \\lim_{x \\to -5+0}\\dfrac{x}{x+5}=\\boldsymbol{-\\infty}$</p>",
    // 関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to -2}\\dfrac{x^{3}+3x^{2}-4}{x^{3}+8}$": "<p>　$\\displaystyle \\lim_{x \\to -2}\\dfrac{x^{3}+3x^{2}-4}{x^{3}+8}$</p><p>$\\displaystyle =\\lim_{x \\to -2}\\dfrac{(x+2)^{2}(x-1)}{(x+2)(x^{2}-2x+4)}$</p><p>$\\displaystyle =\\lim_{x \\to -2}\\dfrac{(x+2)(x-1)}{x^{2}-2x+4}$</p><p>$\\displaystyle =\\dfrac{0 \\cdot (-3)}{12}$</p><p>$=\\boldsymbol{0}$</p>",
    //普通関数，ごよ１１
    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{1}{x} \\left(\\dfrac{3}{x+3}-1\\right)$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{1}{x} \\left(\\dfrac{3}{x+3}-1\\right)$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{1}{x}\\left(\\dfrac{-x}{x+3}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\left(-\\dfrac{1}{x+3}\\right)$</p><p>$ =\\boldsymbol{-\\dfrac{1}{3}}$</p>",
    //普通関数，ごよ１２
    "$\\displaystyle \\lim_{x \\to 2}\\dfrac{-2x+4}{\\sqrt{2x}-\\sqrt{x+2}}$": "<p>　$\\displaystyle \\lim_{x \\to 2}\\dfrac{-2x+4}{\\sqrt{2x}-\\sqrt{x+2}}$</p><p>$\\displaystyle =\\lim_{x \\to 2}\\dfrac{-2x+4}{2x-(x+2)} \\cdot \\left(\\sqrt{2x}+\\sqrt{x+2}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to 2}\\dfrac{-2x+4}{x-2} \\cdot \\left(\\sqrt{2x}+\\sqrt{x+2}\\right)$</p><p>$\\displaystyle =(-2) \\cdot \\left(\\sqrt{4}+\\sqrt{4} \\right)$</p><p>$=\\boldsymbol{-8}$</p>",
    //有理化関数，ごよ１３
    "$\\displaystyle \\lim_{x \\to \\infty}\\{\\log_2 (8x^2+2)-2\\log_2 (x+3)\\}$": "<p>　$\\displaystyle \\lim_{x \\to \\infty}\\{\\log_2 (8x^2+2)-2\\log_2 (x+3)\\}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\{\\log_2 (8x^2+2)-\\log_2 (x+3)^2\\}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} \\log_2 \\dfrac{8x^2+2}{(x+3)^2}$</p><p>$\\displaystyle =\\lim_{x \\to \\infty} \\log_2 \\dfrac{8+\\dfrac{2}{x^2}}{ \\left(1+\\dfrac{3}{x}\\right)^2}$</p><p>$\\displaystyle =\\log_2 8$</p><p>$=\\boldsymbol{3}$</p>",
    //対数，ごよ１６
    "$\\displaystyle \\lim_{x \\to \\infty}\\left(\\dfrac{b}{a}x-\\dfrac{b}{a}\\sqrt{x^{2}-a^{2}}\\right)$　$( \\ a,b \\ は正の実数)$": "<p>　$\\displaystyle \\lim_{x \\to \\infty}\\left(\\dfrac{b}{a}x-\\dfrac{b}{a}\\sqrt{x^{2}-a^{2}}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\dfrac{b}{a}\\left(x-\\sqrt{x^{2}-a^{2}}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to \\infty}\\dfrac{b}{a}\\left(\\dfrac{a^2}{x+\\sqrt{x^{2}-a^{2}}}\\right)$</p><p>$=\\boldsymbol{0}$</p>",
    //双曲線の漸近線，アプリ版専用
    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{1-\\cos x}{x\\sin x}$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{1-\\cos x}{x\\sin x} \\cdot \\dfrac{1+\\cos x}{1+\\cos x}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{\\sin^{2} x}{x\\sin x (1+\\cos x)}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{\\sin x}{x}\\cdot \\dfrac{1}{1+\\cos x}$</p><p>$=1\\cdot \\dfrac{1}{2}=\\boldsymbol{\\dfrac{1}{2}}$</p>",
    // 三角関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin \\left(\\sin \\dfrac{x}{\\pi}\\right)}{\\pi x}$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin \\left(\\sin \\dfrac{x}{\\pi}\\right)}{\\pi x}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\dfrac{\\sin \\left(\\sin \\dfrac{x}{\\pi}\\right)}{\\sin \\dfrac{x}{\\pi}}\\cdot \\dfrac{\\sin \\dfrac{x}{\\pi}}{\\dfrac{x}{\\pi}}\\cdot \\dfrac{1}{\\pi^{2}}$</p><p>$=\\boldsymbol{\\dfrac{1}{\\pi^{2}}}$</p>",
    // 三角関数の極限，サイトの例題
    "$\\displaystyle \\lim_{x \\to \\frac{\\pi}{2}} \\dfrac{\\cos x}{2x-\\pi}$": "<p>　$\\displaystyle \\lim_{x \\to \\frac{\\pi}{2}} \\dfrac{\\cos x}{2x-\\pi}$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{\\cos \\left(t+\\dfrac{\\pi}{2}\\right)}{2t}　\\left(t=x-\\dfrac{\\pi}{2}\\right)$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\dfrac{-\\sin t}{2t}$</p><p>$\\displaystyle =\\lim_{t \\to 0} \\left(-\\dfrac{1}{2} \\right)\\dfrac{\\sin t}{t}$</p><p>$=\\boldsymbol{-\\dfrac{1}{2}}$</p>",
    //三角関数，ごよ１８
    "$\\displaystyle \\lim_{x \\to 0} \\dfrac{\\tan 3x}{\\sin 5x}$": "<p>　$\\displaystyle \\lim_{x \\to 0} \\dfrac{\\tan 3x}{\\sin 5x}$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\dfrac{\\tan 3x}{3x} \\cdot \\dfrac{5x}{\\sin 5x} \\cdot \\dfrac{3}{5}$</p><p>$\\displaystyle =\\lim_{x \\to 0} \\dfrac{\\sin 3x}{3x} \\cdot \\dfrac{1}{\\cos 3x} \\cdot\\dfrac{5x}{\\sin 5x} \\cdot \\dfrac{3}{5}$</p><p>$\\displaystyle =1 \\cdot 1 \\cdot 1 \\cdot \\dfrac{3}{5}$</p><p>$=\\boldsymbol{\\dfrac{3}{5}}$</p>",
    //三角関数，2023東京都市大，元はごよさんの問題
    "$\\displaystyle \\lim_{x \\to 0} \\dfrac{\\sin 3x-\\sin 7x}{\\sin 2x}$": "<p>　$\\displaystyle \\lim_{x \\to 0}\\dfrac{\\sin 3x-\\sin 7x}{\\sin 2x}$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\left(\\dfrac{\\sin 3x}{\\sin 2x}-\\dfrac{\\sin 7x}{\\sin 2x}\\right)$</p><p>$\\displaystyle =\\lim_{x \\to 0}\\left(\\dfrac{\\sin 3x}{3x}\\cdot\\dfrac{2x}{\\sin 2x}\\cdot\\dfrac{3}{2}-\\dfrac{\\sin 7x}{7x}\\cdot\\dfrac{2x}{\\sin 2x}\\cdot\\dfrac{7}{2}\\right)$</p><p>$=1\\cdot 1\\cdot \\dfrac{3}{2}-1\\cdot 1\\cdot \\dfrac{7}{2}$</p><p>$=\\boldsymbol{-2}$</p>",
    //三角関数，2022東京都市大
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+2}+\\dfrac{1}{n+4}+\\cdots+\\dfrac{1}{3n}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n+2}+\\dfrac{1}{n+4}+\\cdots+\\dfrac{1}{n+2n}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\frac{1}{n+2k}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\frac{1}{n}\\sum_{k=1}^{n}\\frac{1}{1+2\\dfrac{k}{n}}$</p><p>$\\displaystyle =\\int_{0}^{1}\\dfrac{1}{1+2x}\\,dx$</p><p>$\\displaystyle =\\left[\\frac{1}{2}\\log(1+2x)\\right]_{0}^{1}$</p><p>$\\displaystyle =\\boldsymbol{\\frac{1}{2}\\log3}$</p>",
    // 区分求積，サイトの例題
    "$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n}\\left(\\sin^{2}\\dfrac{\\pi}{4n}+\\sin^{2}\\dfrac{2\\pi}{4n}+\\cdots+\\sin^{2}\\dfrac{\\pi}{4}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\dfrac{1}{n}\\left(\\sin^{2}\\dfrac{\\pi}{4n}+\\sin^{2}\\dfrac{2\\pi}{4n}+\\cdots+\\sin^{2}\\dfrac{\\pi}{4}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=1}^{n}\\sin^{2}\\dfrac{k\\pi}{4n}$</p><p>$\\displaystyle =\\int_{0}^{1}\\sin^{2}\\dfrac{\\pi x}{4}\\,dx$</p><p>$\\displaystyle =\\int_{0}^{1}\\dfrac{1}{2}\\left(1-\\cos\\dfrac{\\pi x}{2}\\right)\\,dx$</p><p>$\\displaystyle =\\left[\\dfrac{1}{2}x-\\dfrac{1}{\\pi}\\sin\\dfrac{\\pi x}{2}\\right]_{0}^{1}$</p><p>$=\\boldsymbol{\\dfrac{\\pi-2}{2\\pi}}$</p>",
    // 区分求積
    "$\\displaystyle \\lim_{n \\to \\infty} \\sum\\limits_{k=1}^{n} \\sqrt{\\dfrac{n+k}{n^3}}$": "<p>　$\\displaystyle \\lim_{n \\to \\infty} \\sum\\limits_{k=1}^n  \\sqrt{\\dfrac{n+k}{n^3}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty} \\dfrac{1}{n} \\sum\\limits_{k=1}^n \\sqrt{1+\\dfrac{k}{n}}$</p><p>$\\displaystyle =\\int_{0}^{1} (1+x)^\\frac{1}{2} dx$</p><p>$\\displaystyle =\\left[\\dfrac{2}{3} (1+x)^\\frac{3}{2} \\right]^1_0$</p><p>$=\\boldsymbol{\\dfrac{2}{3}\\left(2\\sqrt{2}-1\\right)}$</p>",
    //区分求積，ごよ１９
    "$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n^{2}+1^{2}}+\\dfrac{2}{n^{2}+2^{2}}+\\dfrac{3}{n^{2}+3^{2}}+\\cdots+\\dfrac{1}{2n}\\right)$": "<p>　$\\displaystyle \\lim_{n \\to \\infty}\\left(\\dfrac{1}{n^{2}+1^{2}}+\\dfrac{2}{n^{2}+2^{2}}+\\dfrac{3}{n^{2}+3^{2}}+\\cdots+\\dfrac{1}{2n}\\right)$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\sum_{k=1}^{n}\\frac{k}{n^{2}+k^{2}}$</p><p>$\\displaystyle =\\lim_{n \\to \\infty}\\dfrac{1}{n}\\sum_{k=1}^{n}\\frac{\\dfrac{k}{n}}{1+\\left(\\dfrac{k}{n}\\right)^{2}}$</p><p>$\\displaystyle =\\int_{0}^{1}\\dfrac{x}{1+x^{2}}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{2}\\int_{0}^{1}\\dfrac{2x}{1+x^{2}}\\,dx$</p><p>$\\displaystyle =\\dfrac{1}{2}\\Bigl[\\log(1+x^{2})\\Bigr]_{0}^{1}$</p><p>$\\displaystyle =\\boldsymbol{\\dfrac{1}{2}\\log 2}$</p>",
    //区分求積，アプリ版専用
    "$\\displaystyle \\lim_{x \\to \\infty} \\dfrac{[3x]}{x}$": "<p>$3x-1 &lt; [3x] \\leqq 3x$ が成り立つ．各辺 $x$ で割ると</p><p style=\"text-align: center\">$\\dfrac{3x-1}{x} &lt; \\dfrac{[3x]}{x} \\leqq \\dfrac{3x}{x}$</p><p style=\"text-align: center\">$\\displaystyle 3-\\dfrac{1}{x} &lt; \\dfrac{[3x]}{x} \\leqq 3$</p><p>$\\displaystyle \\lim_{x \\to \\infty} \\left(3-\\dfrac{1}{x} \\right)=3$ だから $\\displaystyle \\lim_{x \\to \\infty} \\dfrac{[3x]}{x}=\\boldsymbol{3}$</p>",
    //ガウス，ごよ１７
    "$\\displaystyle \\lim_{x \\to 1}\\left(2x-[x]\\right)\\left([x]+1\\right)$": "<p>　$\\displaystyle \\lim_{x \\to 1+0}\\left(2x-[x]\\right)\\left([x]+1\\right)$</p><p>$=(2-1)(1+1)$</p><p>$=2$</p><p>　$\\displaystyle \\lim_{x \\to 1-0}\\left(2x-[x]\\right)\\left([x]+1\\right)$</p><p>$=(2-0)(0+1)$</p><p>$=2$</p><p>　$\\displaystyle \\therefore \\ \\lim_{x \\to 1}\\left(2x-[x]\\right)\\left([x]+1\\right)=\\boldsymbol{2}$</p>",
    //ガウス，片側極限
                ],

        "b": [
                ],

        "c": ['Level 1 Super Rare Item 1'],
        "d": ['Level 1 Super Rare Item 1']
    },




    "2": { // Level 2
        "a": ['Level 2 Common Item 1', 'Level 2 Common Item 2'],
        "b": ['Level 2 Rare Item 1', 'Level 2 Rare Item 2'],
        "c": ['Level 2 Super Rare Item 1', 'Level 2 Super Rare Item 2'],
        "d": ['Level 1 Super Rare Item 1']
    },
    "3": { // Level 3
        "a": ['Level 3 Common Item 1', 'Level 3 Common Item 2'],
        "b": ['Level 3 Rare Item 1'],
        "c": ['Level 3 Super Rare Item 1', 'Level 3 Super Rare Item 2'],
        "d": ['Level 1 Super Rare Item 1']
    }
};